extends RefCounted
## Все игровые данные: постройки, профессии, окрасы и имена котиков.

# карта: в 5 раз больше прежней (56×40)
const W := 126
const H := 90
const OLD_W := 56
const OLD_H := 40
const T := 16

const DEFS := {
	"t_grass": {"name": "Земля", "cost": 0, "unlock": 0, "terra": 0, "paint": true, "desc": "Насыпать землю на воду или песок. Бесплатно — расширяйте остров!"},
	"t_sand": {"name": "Песок", "cost": 0, "unlock": 0, "terra": 2, "paint": true, "desc": "Насыпать песок — получится пляж. Бесплатно."},
	"t_hill": {"name": "Холм", "cost": 0, "unlock": 0, "terra": 3, "paint": true, "desc": "Насыпать холм. На холмах можно строить, а дома оттуда с видом — уютнее. Бесплатно."},
	"t_mountain": {"name": "Горы", "cost": 0, "unlock": 0, "terra": 4, "paint": true, "desc": "Поднять горы. В горах строят только жильё, дороги и украшения. Бесплатно."},
	"t_dry": {"name": "Сухая трава", "cost": 0, "unlock": 0, "terra": 5, "paint": true, "desc": "Калифорнийская сухая трава и кустарник. Бесплатно."},
	"t_meadow": {"name": "Луг", "cost": 0, "unlock": 0, "terra": 6, "paint": true, "desc": "Цветущий луг с маками. Бесплатно."},
	"t_water": {"name": "Вода", "cost": 0, "unlock": 0, "terra": 1, "paint": true, "desc": "Убрать сушу: здесь снова будет вода. Бесплатно. Под дорогой получится мост."},
	"road": {"name": "Дорога (2 полосы)", "cost": 3, "unlock": 0, "walk": true, "paint": true, "desc": "По дорогам котики ездят на машинах на работу и домой. На воде получается мост (8 мон.)."},
	"parking": {"name": "Парковка", "cost": 10, "unlock": 0, "parking": 4, "walk": true, "up": [10, 20], "desc": "Стоянка на 4 машины у дороги. Котики оставляют здесь машины и идут пешком. Без парковок машины стоят прямо на дорогах — бывают пробки!"},
	"garage": {"name": "Паркинг", "cost": 90, "unlock": 8, "size": 2, "parking": 20, "build": 8.0, "up": [70, 140], "desc": "Многоэтажный паркинг на 20 машин. Ставьте рядом с офисами и чудесами."},
	"highway": {"name": "Магистраль", "cost": 6, "unlock": 5, "walk": false, "paint": true, "desc": "Широкое шоссе: по 2 полосы в каждую сторону, машины едут быстрее и обгоняют. Пешеходам сюда нельзя. Дома к магистрали не подключаются — нужна обычная дорога."},
	"oneway": {"name": "Одностороннее движение", "cost": 0, "free": true, "unlock": 0, "paint": true, "desc": "Проведите по дороге — она станет односторонней в эту сторону, и машины поедут по ней в две полосы. Нажатие на дорогу меняет направление по кругу, ещё раз — снова двустороннее. Бесплатно."},
	"rail": {"name": "Железная дорога", "cost": 6, "unlock": 6, "walk": true, "paint": true, "desc": "Рельсы для поездов. Поезд сам ходит между вокзалами и платформами одной линии, а котики ездят на нём в другие районы. Через дорогу получится переезд со шлагбаумом, через воду — мост."},
	"crossing": {"name": "Железнодорожный переезд", "cost": 6, "unlock": 99999, "walk": true, "desc": "Когда идёт поезд, шлагбаум закрывается и машины ждут."},
	"platform": {"name": "Платформа", "cost": 50, "unlock": 6, "jobs": 1, "job": "conductor", "hub": "rail", "need_rail": true, "build": 4.0, "look": {"wall": "efe6d6", "roof": "shed", "rc": "2f8a4f", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "train", "sc": "2f8a4f", "fg": "ffffff", "h": 16}, "desc": "Маленькая остановка поезда. Ставьте вплотную к рельсам."},
	"station": {"name": "Вокзал «Юнион»", "cost": 160, "unlock": 10, "size": 2, "jobs": 4, "job": "conductor", "hub": "rail", "need_rail": true, "nopad": true, "shop": 0.6, "service": 5, "sradius": 8, "build": 10.0, "up": [120, 240], "look": {"wall": "f2dcc0", "roof": "gable", "rc": "c8553d", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "train", "sc": "c8553d", "fg": "ffffff", "h": 30, "extra": ["tower"]}, "desc": "Большой вокзал с часовой башней. Ставьте вплотную к рельсам — поезд будет останавливаться здесь."},
	"airport": {"name": "Аэропорт", "cost": 450, "unlock": 25, "size": 3, "jobs": 8, "job": "pilot", "hub": "air", "shop": 1.2, "tourism": 1.5, "build": 20.0, "look": {"wall": "e8eef4", "roof": "flat", "rc": "9aa6b8", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "h": 64, "extra": ["runway"]}, "desc": "Самолёты летают в другие аэропорты вашего города. Нужно хотя бы два аэропорта — иначе лететь некуда. Отлично связывает дальние острова!"},
	"path": {"name": "Тротуар", "cost": 2, "unlock": 0, "walk": true, "paint": true, "desc": "Пешеходная дорожка: по ней котики ходят быстрее."},

	"house": {"name": "Домик", "cost": 30, "unlock": 0, "cap": 3, "build": 4.0, "up": [25, 50], "desc": "Домик с ушками на крыше. Живут 3 котика."},
	"cottage": {"name": "Коттедж", "cost": 80, "unlock": 8, "size": 2, "cap": 5, "build": 9.0, "up": [60, 120], "desc": "Большой семейный дом с садиком. Живут 5 котиков."},
	"villa": {"name": "Вилла с бассейном", "cost": 140, "unlock": 14, "size": 2, "cap": 4, "happy": 6, "radius": 3, "build": 10.0, "up": [100, 200], "desc": "Белая вилла в калифорнийском стиле. Бассейн, шезлонги и вид на океан."},
	"apartments": {"name": "Многоэтажка", "cost": 200, "unlock": 20, "size": 2, "cap": 11, "build": 14.0, "up": [150, 300], "desc": "Многоквартирный дом с балкончиками. Живут 11 котиков."},

	"pier": {"name": "Рыбный причал", "cost": 25, "unlock": 0, "jobs": 2, "job": "fisher", "food": 0.3, "food_per": 0.25, "need_water": true, "build": 3.0, "up": [20, 40], "store_food": 40, "desc": "Ставится у воды. Рыбаки ловят рыбку для всего города."},
	"shop": {"name": "Магазин", "cost": 40, "unlock": 2, "jobs": 2, "job": "seller", "shop": 0.5, "leisure": true, "build": 4.0, "up": [30, 60], "desc": "Магазин клубков и всякой всячины. Котики заходят за покупками."},
	"icecream": {"name": "Киоск мороженого", "cost": 30, "unlock": 2, "jobs": 1, "job": "icecream", "shop": 0.4, "happy": 3, "radius": 3, "leisure": true, "build": 3.0, "desc": "Рыбное мороженое в вафельном рожке — хит пляжного сезона."},
	"bakery": {"name": "Пекарня", "cost": 45, "unlock": 4, "jobs": 2, "job": "baker", "food": 0.1, "food_per": 0.2, "shop": 0.3, "leisure": true, "build": 4.0, "up": [35, 70], "store_food": 60, "desc": "Свежие рыбные пирожки каждое утро."},
	"sushi": {"name": "Суши-бар", "cost": 60, "unlock": 5, "jobs": 2, "job": "sushi", "food": 0.15, "food_per": 0.15, "shop": 0.6, "leisure": true, "build": 4.0, "store_food": 40, "desc": "Роллы с лососем и тунцом — котики в восторге."},
	"pizzeria": {"name": "Пиццерия", "cost": 55, "unlock": 7, "jobs": 2, "job": "pizza", "food": 0.1, "food_per": 0.15, "shop": 0.6, "leisure": true, "build": 4.0, "desc": "Пицца «Четыре рыбки» прямо из печи."},
	"groomer": {"name": "Груминг-салон", "cost": 50, "unlock": 8, "jobs": 2, "job": "groomer", "shop": 0.6, "happy": 4, "radius": 3, "leisure": true, "build": 4.0, "desc": "Стрижка, расчёсывание и бантики. После салона котики сияют!"},
	"cafe": {"name": "Котокафе", "cost": 70, "unlock": 6, "jobs": 3, "job": "barista", "shop": 0.9, "happy": 6, "radius": 4, "leisure": true, "build": 5.0, "up": [50, 100], "desc": "Молочный латте и пирожные. Любимое место встреч."},
	"gym": {"name": "Фитнес-клуб", "cost": 60, "unlock": 6, "jobs": 2, "job": "trainer", "shop": 0.5, "leisure": true, "build": 5.0, "desc": "Котики качают лапки и бегают на дорожке за лазерной точкой."},
	"cinema": {"name": "Кинотеатр", "cost": 90, "unlock": 10, "jobs": 2, "job": "usher", "shop": 0.7, "happy": 6, "radius": 4, "leisure": true, "build": 6.0, "desc": "Премьеры, попкорн и огни над входом."},

	"blogstudio": {"name": "Блог-студия", "cost": 55, "unlock": 4, "jobs": 2, "job": "blogger", "shop": 0.6, "build": 4.0, "desc": "Здесь снимают ролики «Мой день в Котограде». Лайк, подписка, мур!"},
	"farm": {"name": "Ферма", "cost": 70, "unlock": 3, "size": 2, "jobs": 3, "job": "farmer", "food": 0.4, "food_per": 0.3, "nopad": true, "build": 6.0, "up": [50, 100], "store_food": 200, "desc": "Грядки с кошачьей мятой и огород. Много еды для города."},
	"construction": {"name": "Стройконтора", "cost": 120, "unlock": 8, "size": 2, "jobs": 4, "job": "builder", "builders": true, "vehicle": "truck", "build": 8.0, "up": [90, 180], "desc": "Строители в касках. С ними все стройки идут быстрее!"},
	"itoffice": {"name": "Айти-компания", "cost": 140, "unlock": 12, "size": 2, "jobs": 6, "job": "developer", "shop": 1.4, "build": 10.0, "up": [110, 220], "desc": "Разработчики в худи пишут код и пьют молочный раф. Стартап «Мяугл»."},
	"office": {"name": "Офис", "cost": 150, "unlock": 15, "size": 2, "jobs": 8, "job": "clerk", "shop": 1.2, "build": 12.0, "up": [120, 240], "store_coins": 1000, "desc": "Котики в пиджаках и галстуках перекладывают важные бумажки."},
	"exchange": {"name": "Биржа", "cost": 260, "unlock": 22, "size": 2, "jobs": 6, "job": "trader", "shop": 2.6, "build": 14.0, "store_coins": 6000, "desc": "Трейдеры следят за котировками рыбы и клубков. Акции только растут!"},
	"studio": {"name": "Киностудия", "cost": 220, "unlock": 18, "size": 2, "jobs": 6, "job": "actor", "shop": 1.8, "happy": 8, "radius": 5, "vehicle": "van", "build": 14.0, "desc": "Здесь снимают блокбастеры про котиков. Звёзды в тёмных очках!"},
	"factory": {"name": "Фабрика клубков", "cost": 180, "unlock": 20, "size": 2, "jobs": 8, "job": "worker", "shop": 1.5, "smoke": true, "build": 12.0, "up": [140, 280], "desc": "Здесь сматывают клубочки для всего острова."},

	"townhall": {"name": "Мэрия", "cost": 150, "unlock": 8, "size": 2, "jobs": 4, "job": "official", "service": 10, "sradius": 12, "build": 12.0, "store_coins": 3000, "desc": "Сердце города. Здесь мэр и чиновники решают важные кошачьи вопросы."},
	"lifeguard": {"name": "Спасательная вышка", "cost": 35, "unlock": 3, "jobs": 1, "job": "lifeguard", "need_water": true, "service": 4, "sradius": 7, "build": 3.0, "desc": "Спасатель в красных шортах следит за пляжем."},
	"post": {"name": "Почта", "cost": 50, "unlock": 6, "jobs": 2, "job": "mail", "service": 5, "sradius": 8, "vehicle": "mail", "build": 5.0, "desc": "Почтальоны развозят письма и посылки."},
	"school": {"name": "Школа", "cost": 120, "unlock": 10, "size": 2, "jobs": 4, "job": "teacher", "service": 10, "sradius": 9, "vehicle": "bus", "build": 10.0, "up": [90, 180], "desc": "Учителя в очках учат котят считать рыбок."},
	"police": {"name": "Полиция", "cost": 80, "unlock": 10, "jobs": 3, "job": "police", "service": 8, "sradius": 8, "vehicle": "police", "build": 6.0, "up": [60, 120], "desc": "Полицейские патрулируют улицы на машине с мигалкой."},
	"hospital": {"name": "Больница", "cost": 160, "unlock": 12, "size": 2, "jobs": 4, "job": "doctor", "service": 12, "sradius": 9, "vehicle": "ambulance", "build": 12.0, "up": [120, 240], "desc": "Добрые доктора в белых халатах. Иногда выезжает скорая."},
	"fire": {"name": "Пожарная часть", "cost": 90, "unlock": 15, "jobs": 3, "job": "fire", "service": 8, "sradius": 8, "vehicle": "fire", "build": 6.0, "up": [60, 120], "desc": "Отважные пожарные (и котиков с пальм снимают!)."},
	"library": {"name": "Библиотека", "cost": 70, "unlock": 15, "jobs": 2, "job": "librarian", "service": 6, "sradius": 7, "leisure": true, "build": 6.0, "desc": "Тихое место, где котики читают книжки про рыбалку."},
	"surf": {"name": "Серф-школа", "cost": 45, "unlock": 3, "jobs": 2, "job": "surfer", "need_water": true, "shop": 0.4, "happy": 4, "radius": 3, "leisure": true, "build": 3.0, "desc": "Ставится у воды. Инструкторы учат котиков ловить волну."},

	"flowers": {"name": "Клумба", "cost": 5, "unlock": 0, "happy": 4, "radius": 2, "walk": true, "paint": true, "desc": "Цветочки радуют соседей."},
	"palm": {"name": "Пальма", "cost": 5, "unlock": 0, "happy": 3, "radius": 2, "paint": true, "desc": "Высокая калифорнийская пальма."},
	"umbrella": {"name": "Пляжный зонтик", "cost": 6, "unlock": 0, "happy": 3, "radius": 2, "walk": true, "stroll": true, "desc": "Зонтик и полотенце — можно позагорать."},
	"bench": {"name": "Скамейка", "cost": 6, "unlock": 2, "happy": 3, "radius": 2, "walk": true, "stroll": true, "desc": "Можно присесть и посмотреть на прохожих."},
	"jacaranda": {"name": "Жакаранда", "cost": 8, "unlock": 3, "happy": 5, "radius": 3, "desc": "Сиреневое дерево Лос-Анджелеса, с которого летят лепестки."},
	"cushion": {"name": "Лежанка", "cost": 10, "unlock": 4, "happy": 5, "radius": 2, "walk": true, "stroll": true, "desc": "Мягкая подушка, чтобы вздремнуть."},
	"lantern": {"name": "Фонарь", "cost": 8, "unlock": 4, "happy": 3, "radius": 3, "desc": "Тёплый свет по вечерам."},
	"cattree": {"name": "Когтеточка", "cost": 25, "unlock": 6, "happy": 10, "radius": 3, "stroll": true, "desc": "Можно точить когти и лазать по полочкам!"},
	"fountain": {"name": "Фонтан", "cost": 60, "unlock": 12, "happy": 16, "radius": 4, "stroll": true, "desc": "Журчащая вода — можно смотреть вечно."},
	"playground": {"name": "Детская площадка", "cost": 70, "unlock": 15, "size": 2, "happy": 14, "radius": 5, "walk": true, "stroll": true, "desc": "Качели, горка и песочница."},
	"statue": {"name": "Памятник", "cost": 90, "unlock": 20, "happy": 15, "radius": 5, "stroll": true, "desc": "Памятник Первому Коту — основателю города."},

	"sign": {"name": "Знак «KOTOWOOD»", "cost": 250, "unlock": 14, "size": 2, "wonder": true, "tourism": 2.0, "happy": 25, "radius": 9, "stroll": true, "build": 12.0, "desc": "Огромные буквы на холме — символ города. Все туристы фотографируются!"},
	"pier_wheel": {"name": "Пирс Санта-Мурики", "cost": 320, "unlock": 18, "size": 2, "wonder": true, "tourism": 3.0, "need_water": true, "happy": 25, "radius": 9, "stroll": true, "build": 16.0, "desc": "Колесо обозрения и аттракционы прямо над океаном. Ставится у воды."},
	"observatory": {"name": "Обсерватория Гриффит", "cost": 380, "unlock": 22, "size": 2, "wonder": true, "tourism": 3.5, "happy": 28, "radius": 10, "stroll": true, "build": 18.0, "desc": "Белые купола на холме. Отсюда котики смотрят на звёзды и огни города."},
	"concert": {"name": "Концертный зал Диснейя", "cost": 420, "unlock": 26, "size": 2, "wonder": true, "tourism": 4.0, "happy": 30, "radius": 10, "stroll": true, "build": 18.0, "desc": "Серебряные паруса из стали. Здесь играет кошачий симфонический оркестр."},
	"stadium": {"name": "Стадион «Котоджерс»", "cost": 480, "unlock": 30, "size": 2, "wonder": true, "tourism": 5.0, "happy": 30, "radius": 11, "stroll": true, "build": 20.0, "desc": "Бейсбол, хот-доги и волна на трибунах. Весь город болеет за своих!"},
	"urban_light": {"name": "Городские огни", "cost": 260, "unlock": 16, "size": 2, "wonder": true, "tourism": 2.5, "happy": 25, "radius": 9, "stroll": true, "walk": true, "build": 12.0, "desc": "Роща из старинных уличных фонарей. Вечером здесь все делают фото!"},
	"bowl": {"name": "Голливуд-Боул", "cost": 300, "unlock": 20, "size": 2, "wonder": true, "tourism": 3.0, "happy": 28, "radius": 10, "stroll": true, "build": 16.0, "desc": "Концертная «ракушка» под открытым небом на склоне холма."},
	"chinese": {"name": "Китайский кинотеатр Мяуманна", "cost": 350, "unlock": 24, "size": 2, "wonder": true, "tourism": 3.5, "happy": 28, "radius": 10, "stroll": true, "build": 16.0, "desc": "Кинотеатр-пагода, а у входа — отпечатки лапок кинозвёзд."},
	"capitol": {"name": "Башня Кэпитол-Мурекордс", "cost": 400, "unlock": 28, "size": 2, "wonder": true, "tourism": 4.0, "happy": 30, "radius": 10, "stroll": true, "build": 18.0, "desc": "Круглая башня звукозаписи, похожая на стопку пластинок с иглой."},
	"getty": {"name": "Центр Гетти", "cost": 450, "unlock": 32, "size": 2, "wonder": true, "tourism": 4.5, "happy": 32, "radius": 10, "stroll": true, "need_high": true, "build": 20.0, "desc": "Белый музей на вершине холма с садами и видом на океан. Строится только на холмах и в горах."},
	"tower": {"name": "Кошачья башня", "cost": 600, "unlock": 36, "wonder": true, "tourism": 6.0, "happy": 35, "radius": 9, "stroll": true, "build": 20.0, "desc": "Величайшая когтеточка мира — гордость Котограда!"},

	"trailer": {"name": "Трейлер", "cost": 18, "unlock": 0, "cap": 1, "build": 2.0, "look": {"wall": "d8dce4", "roof": "none", "rc": "8a8fb0", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "h": 16, "extra": ["trailer"]}, "desc": "Серебристый трейлер с гирляндой. Живёт 1 котик."},
	"bungalow": {"name": "Пляжное бунгало", "cost": 40, "unlock": 3, "cap": 2, "happy": 2, "radius": 2, "build": 4.0, "up": [30, 60], "look": {"wall": "f2e6cc", "roof": "gable", "rc": "5fbfb0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "h": 24, "extra": ["porch"]}, "desc": "Домик на пляже с верандой. Живут 2 котика."},
	"townhouse": {"name": "Таунхаус", "cost": 55, "unlock": 6, "cap": 3, "build": 5.0, "up": [40, 80], "look": {"wall": "f7c6a8", "roof": "gable", "rc": "8a5a6a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "h": 28}, "desc": "Узкие разноцветные дома в ряд. Живут 3 котика."},
	"mansion": {"name": "Особняк на холмах", "cost": 160, "unlock": 12, "size": 2, "cap": 4, "happy": 8, "radius": 3, "need_high": true, "build": 10.0, "up": [120, 240], "look": {"wall": "fbfbf8", "roof": "flat", "rc": "c9a77a", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "h": 40, "extra": ["pool", "palm"]}, "desc": "Роскошный особняк с видом на город. Строится только на холмах и в горах! Живут 4 котика."},
	"condo": {"name": "Жилая башня", "cost": 280, "unlock": 24, "size": 2, "cap": 16, "build": 18.0, "up": [200, 400], "look": {"wall": "a8c4e0", "roof": "flat", "rc": "6a7f9a", "win": "glass", "wc": "cfe6f7", "door": "8a5a3b", "h": 62, "extra": ["antenna"]}, "desc": "Стеклянный небоскрёб в Даунтауне. Живут 16 котиков."},
	"techstore": {"name": "Магазин техники", "cost": 70, "unlock": 6, "jobs": 2, "job": "techseller", "shop": 0.8, "leisure": true, "build": 5.0, "up": [60, 120], "look": {"wall": "e8eef6", "roof": "flat", "rc": "3d5a98", "win": "shop", "wc": "cfe6f7", "door": "8a5a3b", "sign": "tv", "sc": "5b8de4", "fg": "ffffff", "h": 24}, "desc": "Ноутбуки, телефоны и игровые приставки."},
	"boutique": {"name": "Бутик", "cost": 60, "unlock": 5, "jobs": 2, "job": "stylist", "shop": 0.8, "leisure": true, "build": 4.0, "look": {"wall": "f6e8f0", "roof": "awning", "rc": "2b2b3a", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "shirt", "sc": "2b2b3a", "fg": "ffd23f", "h": 24, "awn": "2b2b3a"}, "desc": "Модная одежда с Родео-драйв."},
	"bookstore": {"name": "Книжный магазин", "cost": 45, "unlock": 4, "jobs": 2, "job": "bookseller", "shop": 0.5, "leisure": true, "build": 4.0, "look": {"wall": "c9a77a", "roof": "awning", "rc": "3b7a4a", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "book", "sc": "fff4e0", "fg": "8a5a3b", "h": 24, "awn": "3b7a4a"}, "desc": "Книги, комиксы и уютное кресло."},
	"toystore": {"name": "Магазин игрушек", "cost": 45, "unlock": 4, "jobs": 2, "job": "toyseller", "shop": 0.5, "leisure": true, "build": 4.0, "look": {"wall": "ffe08a", "roof": "awning", "rc": "e45b6b", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "ball", "sc": "ffffff", "fg": "e45b6b", "h": 24, "awn": "e45b6b"}, "desc": "Мячики, мышки и лазерные указки."},
	"petshop": {"name": "Зоомагазин", "cost": 50, "unlock": 4, "jobs": 2, "job": "petseller", "shop": 0.5, "leisure": true, "build": 4.0, "look": {"wall": "cfeee0", "roof": "awning", "rc": "5fae73", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "paw", "sc": "ffffff", "fg": "5fae73", "h": 24, "awn": "5fae73"}, "desc": "Корм, лежанки и рыбки в аквариумах."},
	"florist": {"name": "Цветочный магазин", "cost": 40, "unlock": 3, "jobs": 1, "job": "florist", "shop": 0.4, "happy": 3, "radius": 2, "leisure": true, "build": 3.0, "look": {"wall": "fde4ef", "roof": "awning", "rc": "ff8fab", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "flower", "sc": "ffffff", "fg": "ff6b8b", "h": 22, "awn": "ff8fab"}, "desc": "Букеты из кошачьей мяты."},
	"pharmacy": {"name": "Аптека", "cost": 55, "unlock": 6, "jobs": 2, "job": "pharmacist", "shop": 0.5, "service": 4, "sradius": 6, "build": 4.0, "look": {"wall": "f4f7fb", "roof": "flat", "rc": "5fae73", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "cross", "sc": "5fae73", "fg": "ffffff", "h": 24}, "desc": "Витамины для шерсти и пластыри для лапок."},
	"supermarket": {"name": "Супермаркет", "cost": 140, "unlock": 10, "size": 2, "jobs": 5, "job": "cashier", "shop": 1.2, "food": 0.2, "food_per": 0.1, "store_food": 400, "leisure": true, "build": 10.0, "up": [100, 200], "look": {"wall": "f2f2ea", "roof": "flat", "rc": "e45b6b", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "cart", "sc": "e45b6b", "fg": "ffffff", "h": 34, "extra": ["carts"]}, "desc": "Огромный магазин: еда и всё для дома. Хранит много еды."},
	"mall": {"name": "Торговый центр", "cost": 300, "unlock": 22, "size": 2, "jobs": 8, "job": "mallclerk", "shop": 2.4, "happy": 8, "radius": 5, "leisure": true, "build": 16.0, "up": [200, 400], "look": {"wall": "e8dcc6", "roof": "flat", "rc": "c9a77a", "win": "glass", "wc": "cfe6f7", "door": "8a5a3b", "sign": "star", "sc": "ff8fab", "fg": "ffffff", "h": 44, "extra": ["flag"]}, "desc": "Десятки магазинов под одной крышей."},
	"burger": {"name": "Бургерная", "cost": 50, "unlock": 4, "jobs": 2, "job": "burgercook", "food": 0.1, "food_per": 0.15, "shop": 0.5, "leisure": true, "build": 4.0, "look": {"wall": "fff4e0", "roof": "awning", "rc": "e45b6b", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "burger", "sc": "ffd23f", "fg": "a0603a", "h": 24, "awn": "e45b6b"}, "desc": "Рыбные бургеры In-N-Mur."},
	"tacotruck": {"name": "Тако-фургон", "cost": 30, "unlock": 2, "jobs": 1, "job": "taco", "food": 0.1, "food_per": 0.15, "shop": 0.4, "leisure": true, "build": 2.0, "look": {"wall": "ffd23f", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 16, "extra": ["truck"]}, "desc": "Тако с рыбкой прямо с колёс!"},
	"donut": {"name": "Пончиковая", "cost": 55, "unlock": 5, "jobs": 2, "job": "donut", "food": 0.1, "food_per": 0.1, "shop": 0.6, "happy": 3, "radius": 3, "leisure": true, "build": 4.0, "look": {"wall": "f7e0c8", "roof": "flat", "rc": "a0603a", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "h": 26, "extra": ["bigdonut"]}, "desc": "Огромный пончик на крыше — как в Лос-Анджелесе!"},
	"boba": {"name": "Бабл-ти", "cost": 45, "unlock": 4, "jobs": 1, "job": "boba", "shop": 0.5, "leisure": true, "build": 3.0, "look": {"wall": "e8d8f6", "roof": "awning", "rc": "9b7ad1", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "cup", "sc": "ffffff", "fg": "9b7ad1", "h": 22, "awn": "9b7ad1"}, "desc": "Молочный чай с шариками тапиоки."},
	"juicebar": {"name": "Фреш-бар", "cost": 40, "unlock": 3, "jobs": 1, "job": "juicer", "shop": 0.4, "leisure": true, "build": 3.0, "look": {"wall": "dff4c8", "roof": "awning", "rc": "7cc46a", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "leaf", "sc": "ffffff", "fg": "5fae73", "h": 22, "awn": "7cc46a"}, "desc": "Смузи из авокадо — очень по-калифорнийски."},
	"restaurant": {"name": "Ресторан", "cost": 130, "unlock": 12, "size": 2, "jobs": 5, "job": "waiter", "food": 0.2, "food_per": 0.1, "shop": 1.2, "happy": 6, "radius": 4, "leisure": true, "build": 8.0, "up": [90, 180], "look": {"wall": "f4ead8", "roof": "gable", "rc": "7a1e2a", "win": "grid", "wc": "fff1b0", "door": "8a5a3b", "sign": "fish", "sc": "7a1e2a", "fg": "ffd23f", "h": 36}, "desc": "Ужин при свечах с видом на закат."},
	"market": {"name": "Фермерский рынок", "cost": 70, "unlock": 5, "size": 2, "jobs": 4, "job": "vendor", "food": 0.3, "food_per": 0.15, "shop": 0.6, "store_food": 150, "leisure": true, "build": 5.0, "up": [60, 120], "look": {"wall": "c99a6b", "roof": "awning", "rc": "ff9f43", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "leaf", "sc": "ffffff", "fg": "5fae73", "h": 28, "awn": "ff9f43", "extra": ["stalls"]}, "desc": "Овощи, фрукты и свежая рыба под навесами."},
	"barber": {"name": "Барбершоп", "cost": 40, "unlock": 4, "jobs": 1, "job": "barber", "shop": 0.4, "leisure": true, "build": 3.0, "look": {"wall": "f4f4f8", "roof": "flat", "rc": "e45b6b", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "scissors", "sc": "ffffff", "fg": "e45b6b", "h": 22, "extra": ["pole"]}, "desc": "Стрижка усов и бороды."},
	"spa": {"name": "Спа-салон", "cost": 70, "unlock": 8, "jobs": 2, "job": "masseur", "shop": 0.6, "happy": 5, "radius": 3, "leisure": true, "build": 4.0, "look": {"wall": "e0f4ee", "roof": "flat", "rc": "5fbfb0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "drop", "sc": "ffffff", "fg": "5fbfb0", "h": 24}, "desc": "Массаж лапок и ванны с ромашкой."},
	"yoga": {"name": "Йога-студия", "cost": 50, "unlock": 5, "jobs": 1, "job": "yogi", "shop": 0.4, "happy": 3, "radius": 3, "leisure": true, "build": 3.0, "look": {"wall": "f6eee0", "roof": "flat", "rc": "ffb07a", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "sun", "sc": "ffb07a", "fg": "ffffff", "h": 22}, "desc": "Поза «потягивающийся котик»."},
	"tattoo": {"name": "Тату-салон", "cost": 45, "unlock": 6, "jobs": 1, "job": "tattoo", "shop": 0.5, "leisure": true, "build": 3.0, "look": {"wall": "3b3b4a", "roof": "flat", "rc": "2b2b3a", "win": "shop", "wc": "ff9fc0", "door": "8a5a3b", "sign": "heart", "sc": "2b2b3a", "fg": "ff6b8b", "h": 22}, "desc": "Татуировки с рыбками и сердечками."},
	"dentist": {"name": "Стоматология", "cost": 60, "unlock": 7, "jobs": 2, "job": "dentist", "service": 4, "sradius": 6, "build": 4.0, "look": {"wall": "f4f7fb", "roof": "flat", "rc": "8fd0f0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "tooth", "sc": "8fd0f0", "fg": "ffffff", "h": 24}, "desc": "Чистка клыков без страха."},
	"vet": {"name": "Ветклиника", "cost": 70, "unlock": 6, "jobs": 2, "job": "vet", "service": 6, "sradius": 7, "build": 5.0, "up": [50, 100], "look": {"wall": "e0f4ee", "roof": "flat", "rc": "5fbfb0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "paw", "sc": "5fbfb0", "fg": "ffffff", "h": 24}, "desc": "Прививки и витаминки для котиков."},
	"laundry": {"name": "Прачечная", "cost": 35, "unlock": 3, "jobs": 1, "job": "laundry", "shop": 0.3, "build": 3.0, "look": {"wall": "cfe6f7", "roof": "flat", "rc": "5b8de4", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "drop", "sc": "ffffff", "fg": "5b8de4", "h": 22, "extra": ["washers"]}, "desc": "Стирка плюшевых пледов."},
	"gasstation": {"name": "Заправка", "cost": 50, "unlock": 4, "jobs": 2, "job": "gasman", "shop": 0.6, "build": 4.0, "look": {"wall": "f4f4f8", "roof": "flat", "rc": "e45b6b", "win": "shop", "wc": "9fd3e6", "door": "8a5a3b", "sign": "fuel", "sc": "e45b6b", "fg": "ffffff", "h": 22, "extra": ["pumps"]}, "desc": "Бензин и хот-доги для водителей."},
	"carwash": {"name": "Автомойка", "cost": 40, "unlock": 4, "jobs": 1, "job": "washer", "shop": 0.5, "build": 3.0, "look": {"wall": "cfe6f7", "roof": "flat", "rc": "5b8de4", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "car", "sc": "ffffff", "fg": "5b8de4", "h": 22, "extra": ["bubbles"]}, "desc": "Пена, щётки и сверкающие машины."},
	"autorepair": {"name": "Автосервис", "cost": 55, "unlock": 6, "jobs": 2, "job": "mechanic", "shop": 0.6, "build": 4.0, "look": {"wall": "d8d4cc", "roof": "flat", "rc": "6a6478", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "wrench", "sc": "ffd23f", "fg": "3b3b4a", "h": 22, "extra": ["garage_door"]}, "desc": "Меняем колёса и чиним моторы."},
	"cardealer": {"name": "Автосалон", "cost": 150, "unlock": 14, "size": 2, "jobs": 4, "job": "cardealer", "shop": 1.6, "build": 8.0, "look": {"wall": "e8eef6", "roof": "flat", "rc": "5b8de4", "win": "glass", "wc": "cfe6f7", "door": "8a5a3b", "sign": "car", "sc": "5b8de4", "fg": "ffffff", "h": 32, "extra": ["lotcars"]}, "desc": "Новенькие кабриолеты с открытым верхом."},
	"motel": {"name": "Мотель", "cost": 70, "unlock": 7, "jobs": 1, "job": "receptionist", "shop": 0.6, "tourism": 0.5, "build": 4.0, "look": {"wall": "ffe0a0", "roof": "flat", "rc": "5fbfb0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "bed", "sc": "5fbfb0", "fg": "ffffff", "h": 24, "extra": ["neon"]}, "desc": "Придорожный мотель с неоновой вывеской."},
	"hotel": {"name": "Отель", "cost": 220, "unlock": 16, "size": 2, "jobs": 6, "job": "concierge", "shop": 1.5, "tourism": 1.5, "build": 14.0, "up": [160, 320], "look": {"wall": "f4ead8", "roof": "flat", "rc": "c9a77a", "win": "grid", "wc": "fff1b0", "door": "8a5a3b", "sign": "star", "sc": "c9a77a", "fg": "ffffff", "h": 56, "extra": ["flag"]}, "desc": "Высокий отель с бассейном на крыше. Туристы!"},
	"coworking": {"name": "Коворкинг", "cost": 70, "unlock": 6, "jobs": 3, "job": "freelancer", "shop": 0.8, "build": 5.0, "look": {"wall": "f2e6cc", "roof": "flat", "rc": "5fae73", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "cup", "sc": "5fae73", "fg": "ffffff", "h": 26}, "desc": "Фрилансеры с ноутбуками и кофе."},
	"bank": {"name": "Банк", "cost": 180, "unlock": 12, "size": 2, "jobs": 4, "job": "banker", "shop": 1.0, "store_coins": 8000, "build": 12.0, "up": [150, 300], "look": {"wall": "f4ead8", "roof": "gable", "rc": "c9b48a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "dollar", "sc": "ffd23f", "fg": "3b7a4a", "h": 40, "extra": ["columns"]}, "desc": "Хранилище монеток: сильно поднимает лимит монет."},
	"insurance": {"name": "Страховая компания", "cost": 90, "unlock": 9, "jobs": 3, "job": "insurer", "shop": 1.0, "build": 6.0, "look": {"wall": "d8e6f0", "roof": "flat", "rc": "3d5a98", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "heart", "sc": "3d5a98", "fg": "ffffff", "h": 30}, "desc": "Страхуем хвосты от прищемления дверью."},
	"lawfirm": {"name": "Юридическая фирма", "cost": 110, "unlock": 11, "jobs": 3, "job": "lawyer", "shop": 1.2, "build": 7.0, "look": {"wall": "e8dcc6", "roof": "flat", "rc": "5a4a3a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "scale", "sc": "5a4a3a", "fg": "ffd23f", "h": 32}, "desc": "Адвокаты в строгих костюмах."},
	"adagency": {"name": "Рекламное агентство", "cost": 100, "unlock": 10, "jobs": 3, "job": "marketer", "shop": 1.1, "build": 6.0, "look": {"wall": "ffe8d8", "roof": "flat", "rc": "ff6fae", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "star", "sc": "ff6fae", "fg": "ffffff", "h": 30}, "desc": "Придумывают слоганы для корма."},
	"design": {"name": "Дизайн-бюро", "cost": 80, "unlock": 8, "jobs": 2, "job": "designer", "shop": 0.9, "build": 5.0, "look": {"wall": "f6f0e8", "roof": "flat", "rc": "ff9f43", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "paint", "sc": "ff9f43", "fg": "ffffff", "h": 26}, "desc": "Логотипы, шрифты и мудборды."},
	"architect": {"name": "Архитектурное бюро", "cost": 90, "unlock": 10, "jobs": 2, "job": "architect", "shop": 0.9, "builders": true, "build": 6.0, "look": {"wall": "e0e8f0", "roof": "flat", "rc": "6a7f9a", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "house", "sc": "6a7f9a", "fg": "ffffff", "h": 28}, "desc": "Проектируют когтеточки будущего. Стройки идут чуть быстрее."},
	"gamestudio": {"name": "Студия видеоигр", "cost": 200, "unlock": 16, "size": 2, "jobs": 6, "job": "gamedev", "shop": 2.0, "build": 12.0, "up": [150, 300], "look": {"wall": "2b2b3a", "roof": "flat", "rc": "9b7ad1", "win": "glass", "wc": "9b7ad1", "door": "8a5a3b", "sign": "game", "sc": "9b7ad1", "fg": "5fd3c8", "h": 40, "extra": ["neon"]}, "desc": "Делают хит «Котики против пылесоса»."},
	"datacenter": {"name": "Вычислительный центр", "cost": 260, "unlock": 20, "size": 2, "jobs": 5, "job": "sysadmin", "shop": 2.4, "build": 14.0, "up": [200, 400], "look": {"wall": "c9cfd8", "roof": "flat", "rc": "4a4e69", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "chip", "sc": "4a4e69", "fg": "5fd3c8", "h": 36, "extra": ["servers", "dish"]}, "desc": "Серверы гудят, лампочки мигают. Тут живёт облако."},
	"recording": {"name": "Студия звукозаписи", "cost": 90, "unlock": 9, "jobs": 2, "job": "musician", "shop": 1.0, "build": 6.0, "look": {"wall": "3b3b4a", "roof": "flat", "rc": "2b2b3a", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "note", "sc": "ffd23f", "fg": "2b2b3a", "h": 26}, "desc": "Здесь записывают хиты «Мур-мур-поп»."},
	"radio": {"name": "Радиостанция", "cost": 80, "unlock": 8, "jobs": 2, "job": "dj", "shop": 0.8, "happy": 3, "radius": 4, "build": 5.0, "look": {"wall": "f2e6cc", "roof": "flat", "rc": "e45b6b", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "mic", "sc": "e45b6b", "fg": "ffffff", "h": 26, "extra": ["mast"]}, "desc": "«Котоград FM» — лучшие песни о рыбе."},
	"tvcenter": {"name": "Телецентр", "cost": 220, "unlock": 18, "size": 2, "jobs": 5, "job": "tvhost", "shop": 1.8, "happy": 5, "radius": 5, "build": 12.0, "look": {"wall": "e8eef6", "roof": "flat", "rc": "3d5a98", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "camera", "sc": "3d5a98", "fg": "ffffff", "h": 44, "extra": ["mast", "dish"]}, "desc": "Новости, ток-шоу и прогноз погоды (всегда солнечно)."},
	"newspaper": {"name": "Редакция газеты", "cost": 70, "unlock": 7, "jobs": 2, "job": "journalist", "shop": 0.7, "build": 5.0, "look": {"wall": "e8dcc6", "roof": "flat", "rc": "5a5868", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "book", "sc": "ffffff", "fg": "3b2a3a", "h": 26}, "desc": "«Мурные вести» — свежий номер каждое утро."},
	"theater": {"name": "Театр", "cost": 180, "unlock": 14, "size": 2, "jobs": 4, "job": "stageactor", "shop": 1.2, "happy": 10, "radius": 5, "leisure": true, "build": 10.0, "look": {"wall": "b02e3a", "roof": "gable", "rc": "7a1e2a", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "mask", "sc": "ffd23f", "fg": "7a1e2a", "h": 40, "extra": ["columns", "neon"]}, "desc": "Спектакль «Кот в сапогах» — аншлаг!"},
	"clothing": {"name": "Фабрика одежды", "cost": 160, "unlock": 12, "size": 2, "jobs": 6, "job": "seamstress", "shop": 1.4, "smoke": true, "build": 10.0, "up": [120, 240], "look": {"wall": "f2d0e0", "roof": "saw", "rc": "8a8fb0", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "shirt", "sc": "ff6fae", "fg": "ffffff", "h": 36, "extra": ["chimney"]}, "desc": "Шьют пиджаки, худи и комбинезоны для всего города."},
	"warehouse": {"name": "Склад", "cost": 90, "unlock": 6, "size": 2, "jobs": 3, "job": "courier", "depot": true, "store_food": 800, "build": 6.0, "up": [70, 140], "look": {"wall": "c9a77a", "roof": "saw", "rc": "8a6a48", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "box", "sc": "c9a77a", "fg": "5a3c30", "h": 30, "extra": ["garage_door"]}, "desc": "Коробки, коробки, коробки! Сильно поднимает лимит еды. Принимает лишние товары и сам развозит их своими грузовиками туда, где они нужны."},
	"cargoport": {"name": "Грузовой порт", "cost": 240, "unlock": 18, "size": 2, "jobs": 6, "job": "docker", "export": true, "shop": 2.0, "need_water": true, "store_food": 300, "build": 14.0, "look": {"wall": "d8d4cc", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 40, "extra": ["containers", "crane"]}, "desc": "Краны и контейнеры. Ставится у воды. Покупает лишние товары на экспорт — грузовики везут сюда всё, что не нужно городу."},
	"cottonfield": {"name": "Хлопковое поле", "cost": 60, "unlock": 10, "size": 2, "jobs": 2, "job": "farmer", "nopad": true, "build": 4.0, "up": [45, 90], "look": {"wall": "8bc34a", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 20, "extra": ["cotton"]}, "desc": "Белые коробочки хлопка. Хлопок везут на Фабрику одежды и Фабрику клубков."},
	"wheat": {"name": "Пшеничное поле", "cost": 70, "unlock": 5, "size": 2, "jobs": 2, "job": "farmer", "nopad": true, "build": 5.0, "up": [55, 110], "look": {"wall": "ecc860", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 34, "extra": ["wheat"]}, "desc": "Золотая пшеница и маленькая мельница: здесь сразу мелют муку. Мука нужна пекарням, пиццериям, пончиковым, бургерным и котокафе."},
	"boatdock": {"name": "Лодочная пристань", "cost": 30, "unlock": 3, "need_water": true, "boats": 1, "boat": "boat", "happy": 3, "radius": 3, "walk": true, "stroll": true, "build": 2.0, "look": {"wall": "c9a77a", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 12, "extra": ["deck"]}, "desc": "Деревянные мостки и моторная лодка. Днём котики катаются по заливу. Ставится у воды."},
	"marina": {"name": "Яхт-клуб", "cost": 160, "unlock": 12, "size": 2, "jobs": 2, "job": "captain", "need_water": true, "boats": 3, "boat": "yacht", "shop": 0.8, "happy": 6, "radius": 4, "tourism": 0.5, "leisure": true, "build": 8.0, "up": [120, 240], "look": {"wall": "f4f6fb", "roof": "flat", "rc": "3d5a98", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "anchor", "sc": "3d5a98", "fg": "ffffff", "h": 32, "extra": ["flag"]}, "desc": "Белые яхты под парусами. Днём они выходят в залив с котиками на борту, а туристы приезжают на них посмотреть. Ставится у воды."},
	"powerplant": {"name": "Электростанция", "cost": 200, "unlock": 14, "size": 2, "jobs": 4, "job": "electrician", "shop": 1.2, "service": 6, "sradius": 12, "smoke": true, "build": 12.0, "look": {"wall": "c9c4d6", "roof": "flat", "rc": "6a6478", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "bolt", "sc": "ffd23f", "fg": "3b3b4a", "h": 44, "extra": ["towers"]}, "desc": "Даёт свет всему острову."},
	"solar": {"name": "Солнечная ферма", "cost": 120, "unlock": 10, "size": 2, "jobs": 2, "job": "engineer", "shop": 1.0, "nopad": true, "build": 6.0, "look": {"wall": "3b4a6a", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 24, "extra": ["panels"]}, "desc": "Солнце Калифорнии превращается в электричество."},
	"waterplant": {"name": "Водоочистная станция", "cost": 130, "unlock": 10, "size": 2, "jobs": 3, "job": "plumber", "service": 6, "sradius": 12, "build": 8.0, "look": {"wall": "cfe6f7", "roof": "flat", "rc": "5b8de4", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "drop", "sc": "5b8de4", "fg": "ffffff", "h": 30, "extra": ["tanks"]}, "desc": "Чистая вода из-под крана."},
	"recycling": {"name": "Сортировка мусора", "cost": 90, "unlock": 8, "size": 2, "jobs": 3, "job": "recycler", "service": 5, "sradius": 10, "vehicle": "truck", "build": 6.0, "look": {"wall": "cfeee0", "roof": "saw", "rc": "5fae73", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "recycle", "sc": "5fae73", "fg": "ffffff", "h": 30, "extra": ["garage_door"]}, "desc": "Пластик к пластику, бумага к бумаге."},
	"courthouse": {"name": "Суд", "cost": 170, "unlock": 14, "size": 2, "jobs": 3, "job": "judge", "service": 6, "sradius": 10, "build": 12.0, "look": {"wall": "f4ead8", "roof": "gable", "rc": "c9b48a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "scale", "sc": "c9b48a", "fg": "3b2a3a", "h": 42, "extra": ["columns", "flag"]}, "desc": "Судья в мантии разбирает спор о сметане."},
	"kindergarten": {"name": "Детский сад", "cost": 70, "unlock": 6, "jobs": 2, "job": "nanny", "service": 6, "sradius": 7, "build": 5.0, "look": {"wall": "fff1b0", "roof": "gable", "rc": "ff8fab", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "ball", "sc": "ffffff", "fg": "5b8de4", "h": 26}, "desc": "Котята играют, рисуют и спят после обеда."},
	"university": {"name": "Университет", "cost": 260, "unlock": 20, "size": 2, "jobs": 6, "job": "professor", "service": 12, "sradius": 12, "build": 16.0, "up": [200, 400], "look": {"wall": "e8b4a0", "roof": "gable", "rc": "6b6f9a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "grad", "sc": "6b6f9a", "fg": "ffffff", "h": 48, "extra": ["tower", "flag"]}, "desc": "Факультет мурлыкологии и рыбной экономики."},
	"lab": {"name": "Научная лаборатория", "cost": 200, "unlock": 16, "size": 2, "jobs": 4, "job": "scientist", "shop": 1.4, "build": 12.0, "look": {"wall": "f4f7fb", "roof": "flat", "rc": "5fd3c8", "win": "glass", "wc": "cfeef0", "door": "8a5a3b", "sign": "flask", "sc": "5fd3c8", "fg": "ffffff", "h": 36, "extra": ["dish"]}, "desc": "Учёные изобретают вечную лазерную точку."},
	"metro": {"name": "Станция метро", "cost": 90, "unlock": 10, "jobs": 1, "job": "metroman", "service": 6, "sradius": 10, "walk": false, "build": 6.0, "look": {"wall": "d8d4cc", "roof": "flat", "rc": "e45b6b", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "bus", "sc": "e45b6b", "fg": "ffffff", "h": 20, "extra": ["stairs"]}, "desc": "Подземка: город становится ближе."},
	"busstation": {"name": "Автовокзал", "cost": 80, "unlock": 8, "size": 2, "jobs": 3, "job": "busdriver", "service": 6, "sradius": 10, "vehicle": "bus", "build": 6.0, "look": {"wall": "f2e6cc", "roof": "shed", "rc": "5b8de4", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "bus", "sc": "5b8de4", "fg": "ffffff", "h": 28}, "desc": "Автобусы во все уголки острова."},
	"taxidepot": {"name": "Таксопарк", "cost": 70, "unlock": 7, "jobs": 2, "job": "taxi", "vehicle": "taxi", "service": 3, "sradius": 8, "build": 4.0, "look": {"wall": "ffd23f", "roof": "flat", "rc": "2b2b3a", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "car", "sc": "2b2b3a", "fg": "ffd23f", "h": 22, "extra": ["garage_door"]}, "desc": "Жёлтые такси с шашечками."},
	"helipad": {"name": "Вертолётная площадка", "cost": 150, "unlock": 18, "jobs": 1, "job": "pilot", "tourism": 1.0, "nopad": true, "build": 6.0, "look": {"wall": "6a6478", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 16, "extra": ["helipad"]}, "desc": "Вертолётные экскурсии над побережьем. Вертолёт летает к другим площадкам и аэропортам, а если лететь некуда — облетает город."},
	"skatepark": {"name": "Скейт-парк", "cost": 50, "unlock": 4, "size": 2, "jobs": 1, "job": "skater", "happy": 8, "radius": 4, "walk": true, "stroll": true, "nopad": true, "build": 4.0, "look": {"wall": "c9c4d6", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 24, "extra": ["ramps"]}, "desc": "Рампы и трюки как в Венис-бич."},
	"tennis": {"name": "Теннисный корт", "cost": 40, "unlock": 3, "size": 2, "jobs": 1, "job": "coach", "happy": 6, "radius": 4, "walk": true, "stroll": true, "nopad": true, "build": 3.0, "look": {"wall": "5fae73", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 20, "extra": ["court"]}, "desc": "Мячик туда-сюда, туда-сюда…"},
	"volleyball": {"name": "Пляжный волейбол", "cost": 25, "unlock": 2, "happy": 4, "radius": 3, "walk": true, "stroll": true, "build": 2.0, "look": {"wall": "f1dfa6", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 16, "extra": ["net"]}, "desc": "Сетка на песке у океана."},
	"arcade": {"name": "Игровые автоматы", "cost": 70, "unlock": 7, "jobs": 1, "job": "arcademan", "shop": 0.6, "happy": 4, "radius": 3, "leisure": true, "build": 4.0, "look": {"wall": "2b2b3a", "roof": "flat", "rc": "9b7ad1", "win": "shop", "wc": "ff9fc0", "door": "8a5a3b", "sign": "game", "sc": "9b7ad1", "fg": "ffd23f", "h": 24, "extra": ["neon"]}, "desc": "Пиксельные игры — как эта!"},
	"bowling": {"name": "Боулинг", "cost": 120, "unlock": 10, "size": 2, "jobs": 3, "job": "bowler", "shop": 1.0, "happy": 7, "radius": 4, "leisure": true, "build": 8.0, "look": {"wall": "e8dcc6", "roof": "flat", "rc": "e45b6b", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "bowling", "sc": "e45b6b", "fg": "ffffff", "h": 30, "extra": ["bigpin", "neon"]}, "desc": "Страйк! Кегли разлетаются."},
	"nightclub": {"name": "Ночной клуб", "cost": 130, "unlock": 12, "jobs": 2, "job": "clubdj", "shop": 1.1, "happy": 5, "radius": 4, "leisure": true, "build": 6.0, "look": {"wall": "2b2b3a", "roof": "flat", "rc": "ff6fae", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "sign": "note", "sc": "ff6fae", "fg": "5fd3c8", "h": 28, "extra": ["neon"]}, "desc": "Диско-шар и танцы до утра."},
	"aquarium": {"name": "Океанариум", "cost": 240, "unlock": 18, "size": 2, "jobs": 4, "job": "marinebio", "shop": 1.4, "happy": 12, "radius": 6, "tourism": 1.5, "leisure": true, "build": 14.0, "look": {"wall": "8fd0f0", "roof": "dome", "rc": "5b8de4", "win": "glass", "wc": "5fc8e8", "door": "8a5a3b", "sign": "fish", "sc": "5b8de4", "fg": "ffffff", "h": 40}, "desc": "Акулы, медузы и тысяча рыбок. Котики в восторге!"},
	"zoo": {"name": "Зоопарк", "cost": 200, "unlock": 16, "size": 2, "jobs": 4, "job": "zookeeper", "shop": 1.2, "happy": 12, "radius": 6, "tourism": 1.5, "leisure": true, "nopad": true, "build": 12.0, "look": {"wall": "8ab86a", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 32, "extra": ["zoo"]}, "desc": "Жирафы, пингвины и вольер с мышками."},
	"museum": {"name": "Музей", "cost": 200, "unlock": 15, "size": 2, "jobs": 3, "job": "curator", "happy": 10, "radius": 6, "tourism": 1.0, "leisure": true, "build": 12.0, "look": {"wall": "f4ead8", "roof": "gable", "rc": "c9b48a", "win": "grid", "wc": "9fd3e6", "door": "8a5a3b", "sign": "mask", "sc": "c9b48a", "fg": "3b2a3a", "h": 42, "extra": ["columns"]}, "desc": "Скелет древнего кота и картины с рыбами."},
	"gallery": {"name": "Арт-галерея", "cost": 90, "unlock": 9, "jobs": 1, "job": "artist", "shop": 0.6, "happy": 5, "radius": 4, "leisure": true, "build": 5.0, "look": {"wall": "fbfbf8", "roof": "flat", "rc": "2b2b3a", "win": "glass", "wc": "9fd3e6", "door": "8a5a3b", "sign": "paint", "sc": "2b2b3a", "fg": "ff6fae", "h": 26}, "desc": "Современное искусство: клубок на постаменте."},
	"billboard": {"name": "Билборд", "cost": 20, "unlock": 3, "happy": 2, "radius": 2, "build": 1.0, "look": {"wall": "ffffff", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 24, "extra": ["billboard"]}, "desc": "Огромная реклама корма над дорогой."},
	"watertower": {"name": "Водонапорная башня", "cost": 30, "unlock": 5, "happy": 3, "radius": 3, "build": 2.0, "look": {"wall": "c9c4d6", "roof": "none", "rc": "8a8fb0", "win": "none", "wc": "9fd3e6", "door": "8a5a3b", "h": 32, "extra": ["watertower"]}, "desc": "Старая башня — гордость района."},

	"wildpalm": {"name": "Пальма", "natural": true, "desc": "Дикая пальма. Можно убрать лопаткой за 2 монетки."},
	"agave": {"name": "Агава", "natural": true, "desc": "Колючая агава. Можно убрать лопаткой за 2 монетки."},
	"rock": {"name": "Камень", "natural": true, "desc": "Можно убрать лопаткой за 2 монетки."},
}

const TABS := [
	{"name": "Рельеф", "icon": "t_grass", "tools": ["t_grass", "t_sand", "t_water", "t_hill", "t_mountain", "t_dry", "t_meadow"]},
	{"name": "Транспорт", "icon": "road", "tools": ["road", "oneway", "highway", "path", "parking", "garage", "rail", "platform", "station", "airport"]},
	{"name": "Жильё", "icon": "house", "tools": ["trailer", "house", "bungalow", "townhouse", "cottage", "villa", "mansion", "apartments", "condo"]},
	{"name": "Магазины", "icon": "shop", "tools": ["shop", "techstore", "boutique", "bookstore", "toystore", "petshop", "florist", "pharmacy", "supermarket", "mall"]},
	{"name": "Еда", "icon": "sushi", "tools": ["pier", "farm", "bakery", "cafe", "sushi", "pizzeria", "icecream", "burger", "tacotruck", "donut", "boba", "juicebar", "restaurant", "market"]},
	{"name": "Услуги", "icon": "groomer", "tools": ["groomer", "gym", "barber", "spa", "yoga", "tattoo", "dentist", "vet", "laundry", "gasstation", "carwash", "autorepair", "cardealer", "motel", "hotel"]},
	{"name": "Бизнес", "icon": "blogstudio", "tools": ["blogstudio", "construction", "itoffice", "office", "exchange", "coworking", "bank", "insurance", "lawfirm", "adagency", "design", "architect", "gamestudio", "datacenter"]},
	{"name": "Медиа", "icon": "cinema", "tools": ["cinema", "studio", "recording", "radio", "tvcenter", "newspaper", "theater"]},
	{"name": "Промышленность", "icon": "factory", "tools": ["wheat", "cottonfield", "factory", "clothing", "warehouse", "cargoport", "powerplant", "solar", "waterplant", "recycling"]},
	{"name": "Город", "icon": "townhall", "tools": ["townhall", "lifeguard", "post", "school", "police", "hospital", "fire", "library", "courthouse", "kindergarten", "university", "lab", "metro", "busstation", "taxidepot", "helipad"]},
	{"name": "Отдых", "icon": "umbrella", "tools": ["umbrella", "bench", "cushion", "lantern", "cattree", "fountain", "playground", "surf", "boatdock", "marina", "skatepark", "tennis", "volleyball", "arcade", "bowling", "nightclub", "aquarium", "zoo", "museum", "gallery"]},
	{"name": "Природа", "icon": "palm", "tools": ["flowers", "palm", "jacaranda", "statue", "billboard", "watertower"]},
	{"name": "Чудеса", "icon": "observatory", "tools": ["sign", "urban_light", "pier_wheel", "bowl", "observatory", "chinese", "concert", "capitol", "stadium", "getty", "tower"]},
]

const TOOL_INFO := {
	"hand": {"name": "Лапка", "desc": "Двигай карту, гладь котиков, смотри постройки и машины."},
	"bulldoze": {"name": "Лопатка", "desc": "Убрать постройку (вернётся половина цены) или пальму/камень (2 мон.)."},
}

const PROFESSIONS := {
	"fisher": "Рыбак", "seller": "Продавец", "baker": "Пекарь", "barista": "Бариста", "clerk": "Офисный сотрудник",
	"official": "Чиновник мэрии", "worker": "Рабочий фабрики", "builder": "Строитель", "teacher": "Учитель",
	"doctor": "Врач", "police": "Полицейский", "fire": "Пожарный", "mail": "Почтальон", "librarian": "Библиотекарь",
	"developer": "Разработчик", "blogger": "Блогер", "actor": "Актёр", "surfer": "Серф-инструктор",
	"trainer": "Фитнес-тренер", "icecream": "Мороженщик", "usher": "Киномеханик", "lifeguard": "Спасатель",
	"techseller": "Консультант техники",
	"stylist": "Стилист",
	"bookseller": "Книготорговец",
	"toyseller": "Продавец игрушек",
	"petseller": "Продавец зоотоваров",
	"florist": "Флорист",
	"pharmacist": "Фармацевт",
	"cashier": "Кассир",
	"mallclerk": "Продавец ТЦ",
	"burgercook": "Повар бургеров",
	"taco": "Такверо",
	"donut": "Кондитер",
	"boba": "Чайный мастер",
	"juicer": "Бармен фреш-бара",
	"waiter": "Официант",
	"vendor": "Фермер-торговец",
	"barber": "Барбер",
	"masseur": "Массажист",
	"yogi": "Инструктор йоги",
	"tattoo": "Тату-мастер",
	"dentist": "Стоматолог",
	"vet": "Ветеринар",
	"laundry": "Работник прачечной",
	"gasman": "Заправщик",
	"washer": "Мойщик машин",
	"mechanic": "Механик",
	"cardealer": "Автодилер",
	"receptionist": "Администратор мотеля",
	"concierge": "Консьерж",
	"freelancer": "Фрилансер",
	"banker": "Банкир",
	"insurer": "Страховой агент",
	"lawyer": "Адвокат",
	"marketer": "Маркетолог",
	"designer": "Дизайнер",
	"architect": "Архитектор",
	"gamedev": "Геймдизайнер",
	"sysadmin": "Сисадмин",
	"musician": "Музыкант",
	"dj": "Радиоведущий",
	"tvhost": "Телеведущий",
	"journalist": "Журналист",
	"stageactor": "Актёр театра",
	"seamstress": "Швея",
	"courier": "Курьер",
	"docker": "Докер",
	"electrician": "Электрик",
	"engineer": "Инженер",
	"plumber": "Сантехник",
	"recycler": "Сортировщик",
	"judge": "Судья",
	"nanny": "Воспитатель",
	"professor": "Профессор",
	"scientist": "Учёный",
	"metroman": "Машинист метро",
	"conductor": "Кондуктор",
	"captain": "Капитан яхты",
	"busdriver": "Водитель автобуса",
	"taxi": "Таксист",
	"pilot": "Пилот",
	"skater": "Скейтер",
	"coach": "Тренер по теннису",
	"arcademan": "Смотритель автоматов",
	"bowler": "Работник боулинга",
	"clubdj": "Диджей",
	"marinebio": "Морской биолог",
	"zookeeper": "Смотритель зоопарка",
	"curator": "Куратор музея",
	"artist": "Художник",
	"sushi": "Суши-повар", "pizza": "Пиццайоло", "groomer": "Грумер", "farmer": "Фермер", "trader": "Трейдер",
}

## Одежда новых профессий (старые описаны в sprites.gd).
const JOB_OUTFITS := {
	"captain": {"s": "ffffff", "t": "3d5a98", "w": "ffffff", "l": "ffffff", "hat": "cap", "hc": "ffffff", "badge": true},
	"conductor": {"s": "2f3a5a", "t": "ffffff", "w": "2f3a5a", "l": "2f3a5a", "hat": "cap", "hc": "2f3a5a", "badge": true},
	"fan": {"s": "2f5fb0", "t": "ffffff", "w": "2f5fb0", "l": "3b3b4a", "hat": "cap", "hc": "2f5fb0"},
	"tourist": {"s": "ffb07a", "t": "7fc4e8", "w": "ffb07a", "l": "c8b896", "hat": "straw", "hc": "e8c870", "shades": true},
	"techseller": {"s": "5b8de4", "t": "ffffff", "w": "5b8de4", "l": "3b3b4a", "hat": "cap", "hc": "3d5a98"},
	"stylist": {"s": "2b2b3a", "t": "ffd23f", "w": "ffffff", "l": "2b2b3a", "shades": true},
	"bookseller": {"s": "7a5a48", "t": "c9a77a", "w": "ffffff", "l": "5a4a3a", "glasses": true},
	"toyseller": {"s": "ffd23f", "t": "e45b6b", "w": "ffffff", "l": "5b8de4", "hat": "cap", "hc": "e45b6b"},
	"petseller": {"s": "5fae73", "t": "ffffff", "w": "ffffff", "l": "6b5a4a", "hat": "cap", "hc": "5fae73"},
	"florist": {"s": "ff8fab", "t": "5fae73", "w": "ffffff", "l": "6b5a4a", "hat": "straw", "hc": "e8c870"},
	"pharmacist": {"s": "f4f7fb", "t": "5fae73", "w": "5fae73", "l": "8fb3f2", "glasses": true},
	"cashier": {"s": "e45b6b", "t": "ffffff", "w": "ffffff", "l": "3b3b4a", "hat": "cap", "hc": "e45b6b"},
	"mallclerk": {"s": "ff8fab", "t": "ffffff", "w": "ffffff", "l": "3b3b4a"},
	"burgercook": {"s": "ffffff", "t": "e45b6b", "w": "e45b6b", "l": "3b3b4a", "hat": "cap", "hc": "e45b6b"},
	"taco": {"s": "ff9f43", "t": "5fae73", "w": "ffffff", "l": "3b3b4a", "hat": "sombrero", "hc": "e8c870"},
	"donut": {"s": "ffffff", "t": "ff8fab", "w": "ff8fab", "l": "8a6a4a", "hat": "chef", "hc": "ffffff"},
	"boba": {"s": "9b7ad1", "t": "ffffff", "w": "ffffff", "l": "3b3b4a", "hat": "beret", "hc": "c8a8ff"},
	"juicer": {"s": "7cc46a", "t": "ffffff", "w": "ffffff", "l": "5b7bb0", "hat": "band", "hc": "ffd23f"},
	"waiter": {"s": "2b2b3a", "t": "e45b6b", "w": "ffffff", "l": "2b2b3a"},
	"vendor": {"s": "ff9f43", "t": "ffffff", "w": "ffffff", "l": "4a6fb8", "hat": "straw", "hc": "e8c870"},
	"barber": {"s": "2b2b3a", "t": "e45b6b", "w": "ffffff", "l": "3b3b4a", "hat": "beanie", "hc": "2b2b3a"},
	"masseur": {"s": "5fbfb0", "t": "ffffff", "w": "5fbfb0", "l": "ffffff"},
	"yogi": {"s": "ffb07a", "t": "ffb07a", "w": "ffb07a", "l": "9b7ad1", "hat": "band", "hc": "9b7ad1"},
	"tattoo": {"s": "2b2b3a", "t": "ff6b8b", "w": "2b2b3a", "l": "2b2b3a", "hat": "beanie", "hc": "ff6b8b", "shades": true},
	"dentist": {"s": "8fd0f0", "t": "ffffff", "w": "ffffff", "l": "8fd0f0", "mask": true},
	"vet": {"s": "5fbfb0", "t": "ffffff", "w": "ffffff", "l": "5fbfb0", "steth": true},
	"laundry": {"s": "8fb3f2", "t": "ffffff", "w": "ffffff", "l": "5b7bb0", "hat": "beanie", "hc": "8fb3f2"},
	"gasman": {"s": "e45b6b", "t": "ffd23f", "w": "ffffff", "l": "3b3b4a", "hat": "cap", "hc": "e45b6b"},
	"washer": {"s": "ffd23f", "t": "5b8de4", "w": "ffd23f", "l": "5b8de4", "hat": "sou", "hc": "5b8de4"},
	"mechanic": {"s": "6a7f9a", "t": "6a7f9a", "w": "e8e8e8", "l": "6a7f9a", "hat": "cap", "hc": "ff9f43"},
	"cardealer": {"s": "3d5a98", "t": "ffd23f", "w": "ffffff", "l": "3d5a98", "shades": true},
	"receptionist": {"s": "5fbfb0", "t": "ffd23f", "w": "ffffff", "l": "3b3b4a"},
	"concierge": {"s": "b02e3a", "t": "ffd23f", "w": "ffffff", "l": "2b2b3a", "hat": "top", "hc": "2b2b3a"},
	"freelancer": {"s": "c8a8ff", "t": "c8a8ff", "w": "c8a8ff", "l": "5b7bb0", "glasses": true, "phones": true},
	"banker": {"s": "2f3a5a", "t": "5fae73", "w": "ffffff", "l": "2f3a5a", "glasses": true},
	"insurer": {"s": "5d6573", "t": "3d5a98", "w": "ffffff", "l": "5d6573"},
	"lawyer": {"s": "2b2b3a", "t": "7a1e2a", "w": "ffffff", "l": "2b2b3a"},
	"marketer": {"s": "ff6fae", "t": "ffffff", "w": "ffffff", "l": "2b2b3a", "shades": true},
	"designer": {"s": "2b2b3a", "t": "2b2b3a", "w": "2b2b3a", "l": "2b2b3a", "hat": "beret", "hc": "ff9f43", "glasses": true},
	"architect": {"s": "e8e8e8", "t": "3d5a98", "w": "ffffff", "l": "5d6573", "hat": "hard", "hc": "ffffff", "glasses": true},
	"gamedev": {"s": "9b7ad1", "t": "9b7ad1", "w": "c8a8ff", "l": "3e5a8a", "phones": true},
	"sysadmin": {"s": "2b2b3a", "t": "5fd3c8", "w": "2b2b3a", "l": "3e5a8a", "glasses": true, "phones": true},
	"musician": {"s": "3b3b4a", "t": "e45b6b", "w": "2b2b3a", "l": "2b2b3a", "shades": true, "hat": "beanie", "hc": "2b2b3a"},
	"dj": {"s": "ffd23f", "t": "e45b6b", "w": "ffd23f", "l": "3b3b4a", "phones": true},
	"tvhost": {"s": "3d5a98", "t": "ff6fae", "w": "ffffff", "l": "2b2b3a"},
	"journalist": {"s": "c9a77a", "t": "ffffff", "w": "ffffff", "l": "5d6573", "hat": "beret", "hc": "5a4a3a", "glasses": true},
	"stageactor": {"s": "7a1e2a", "t": "ffd23f", "w": "ffffff", "l": "2b2b3a", "hat": "top", "hc": "2b2b3a"},
	"seamstress": {"s": "ff9fc0", "t": "ffffff", "w": "ffffff", "l": "6b5a4a", "glasses": true},
	"courier": {"s": "8a6a48", "t": "ffd23f", "w": "8a6a48", "l": "8a6a48", "hat": "cap", "hc": "8a6a48"},
	"docker": {"s": "ff9f43", "t": "fff066", "w": "5b8de4", "l": "3e5a8a", "hat": "hard", "hc": "ff9f43"},
	"electrician": {"s": "ffd23f", "t": "3b3b4a", "w": "ffd23f", "l": "3b3b4a", "hat": "hard", "hc": "ffffff"},
	"engineer": {"s": "ffffff", "t": "5fae73", "w": "ffffff", "l": "5b7bb0", "hat": "hard", "hc": "ffffff", "glasses": true},
	"plumber": {"s": "5b8de4", "t": "e45b6b", "w": "5b8de4", "l": "5b8de4", "hat": "cap", "hc": "e45b6b"},
	"recycler": {"s": "5fae73", "t": "fff066", "w": "5fae73", "l": "3b7a4a", "hat": "cap", "hc": "5fae73"},
	"judge": {"s": "2b2b3a", "t": "ffffff", "w": "ffffff", "l": "2b2b3a", "glasses": true},
	"nanny": {"s": "ffd75e", "t": "ff8fab", "w": "ffffff", "l": "8fb3f2", "hat": "band", "hc": "ff8fab"},
	"professor": {"s": "8a6a48", "t": "e45b6b", "w": "ffffff", "l": "5a4a3a", "glasses": true, "hat": "grad", "hc": "2b2b3a"},
	"scientist": {"s": "f4f7fb", "t": "5fd3c8", "w": "ffffff", "l": "5d6573", "goggles": true},
	"metroman": {"s": "e45b6b", "t": "ffffff", "w": "ffffff", "l": "2b2b3a", "hat": "cap", "hc": "2b2b3a"},
	"busdriver": {"s": "5b8de4", "t": "ffd23f", "w": "ffffff", "l": "3d5a98", "hat": "cap", "hc": "3d5a98"},
	"taxi": {"s": "ffd23f", "t": "2b2b3a", "w": "ffd23f", "l": "3b3b4a", "hat": "cap", "hc": "2b2b3a", "shades": true},
	"pilot": {"s": "f4f4f8", "t": "2b2b3a", "w": "ffffff", "l": "2b2b3a", "hat": "cap", "hc": "2b2b3a", "shades": true},
	"skater": {"s": "ff6b6b", "t": "ff6b6b", "w": "ff6b6b", "l": "5b7bb0", "hat": "cap", "hc": "5fd3c8"},
	"coach": {"s": "ffffff", "t": "5fae73", "w": "ffffff", "l": "ffffff", "hat": "band", "hc": "5fae73"},
	"arcademan": {"s": "9b7ad1", "t": "ffd23f", "w": "9b7ad1", "l": "2b2b3a", "phones": true},
	"bowler": {"s": "e45b6b", "t": "ffffff", "w": "ffffff", "l": "2b2b3a"},
	"clubdj": {"s": "2b2b3a", "t": "ff6fae", "w": "2b2b3a", "l": "2b2b3a", "phones": true, "shades": true},
	"marinebio": {"s": "5fc8e8", "t": "ffffff", "w": "5fc8e8", "l": "3e5a8a", "goggles": true},
	"zookeeper": {"s": "b8a070", "t": "5fae73", "w": "b8a070", "l": "8a6a48", "hat": "straw", "hc": "b8a070"},
	"curator": {"s": "5a4a6a", "t": "ffd23f", "w": "ffffff", "l": "5a4a6a", "glasses": true},
	"artist": {"s": "ffffff", "t": "ff6fae", "w": "ffffff", "l": "5b7bb0", "hat": "beret", "hc": "e45b6b"},
}

const CAR_COLORS := ["e45b6b", "5b8de4", "ffd23f", "5fbf9f", "ff9fc0", "f4f4f8", "9b7ad1", "ff9f43"]
const SERVICE_COLORS := {"police": "f4f6fb", "ambulance": "f8f8fb", "fire": "e0483a", "mail": "5b8de4", "bus": "ffd23f", "truck": "ff9f43", "van": "f4f4f8", "taxi": "ffd23f"}

const CAT_COLORS := {
	"ginger": {"name": "рыжий", "a": "f4a259", "b": "dd7a35"},
	"gray": {"name": "серый", "a": "a3adbb", "b": "7d8898"},
	"white": {"name": "белый", "a": "fbf7f2", "b": "e6dace"},
	"black": {"name": "чёрный", "a": "3f3a4a", "b": "2e2a37", "e": "ffd75e", "k": "1c1822"},
	"calico": {"name": "трёхцветный", "a": "fbf7f2", "b": "e0823f"},
	"siamese": {"name": "сиамский", "a": "f1e3c6", "b": "7a5a48", "e": "5aa0e8"},
	"tabby": {"name": "полосатый", "a": "c09068", "b": "8f6446"},
	"cream": {"name": "кремовый", "a": "f6d9a8", "b": "e8bf80"},
	"tuxedo": {"name": "кот во фраке", "a": "2e2a37", "b": "fbf7f2", "e": "8fd36a", "k": "1c1822", "pat": "tux"},
	"tabbyorange": {"name": "рыжий полосатый", "a": "f6b26b", "b": "d9783a", "pat": "stripes"},
	"lilac": {"name": "лиловый", "a": "c8bccc", "b": "a898b0", "e": "f2c14e"},
	"chocolate": {"name": "шоколадный", "a": "7a5240", "b": "5a3a2c", "e": "f2c14e", "k": "2a1a14"},
	"russian": {"name": "русский голубой", "a": "8a9ab0", "b": "7a8aa0", "e": "7fd36a"},
	"bengal": {"name": "бенгальский", "a": "e8b870", "b": "8a5a30", "e": "7fd36a", "pat": "spots"},
	"mainecoon": {"name": "мейн-кун", "a": "9a7458", "b": "6a4a34", "pat": "stripes"},
	"ragdoll": {"name": "рэгдолл", "a": "f6efe4", "b": "8a7468", "e": "5aa0e8", "pat": "mask"},
	"scottish": {"name": "вислоухий", "a": "c8ccd4", "b": "a8acb4", "e": "f2c14e", "pat": "fold"},
	"sphynx": {"name": "сфинкс", "a": "f2c8bc", "b": "e0a898", "e": "5aa0e8", "pat": "bald"},
	"tortie": {"name": "черепаховый", "a": "3f3a4a", "b": "d9783a", "e": "f2c14e", "k": "1c1822", "pat": "patch"},
	"snow": {"name": "снежный", "a": "ffffff", "b": "e8eef6", "e": "5aa0e8"},
	"gingerwhite": {"name": "рыже-белый", "a": "fbf7f2", "b": "f4a259", "pat": "patch"},
	"smoky": {"name": "дымчатый", "a": "5a5868", "b": "8a8898", "e": "f2c14e", "k": "2a2834"},
	"cinnamon": {"name": "коричный", "a": "c8784a", "b": "a85a30"},
	"golden": {"name": "золотистый", "a": "f2d080", "b": "d8a850", "e": "5fae73", "pat": "stripes"},
	"silver": {"name": "серебристый", "a": "d8dce4", "b": "8a8f9a", "e": "5fae73", "pat": "stripes"},
	"blackwhite": {"name": "чёрно-белый", "a": "fbf7f2", "b": "3f3a4a", "pat": "patch"},
}

const CAT_NAMES := ["Барсик", "Мурка", "Пушок", "Рыжик", "Снежок", "Тучка", "Персик", "Котлетка", "Булочка", "Симба",
	"Луна", "Маркиз", "Соня", "Ириска", "Пончик", "Уголёк", "Зефир", "Кекс", "Масяня", "Фунтик", "Мася", "Плюша",
	"Тимоша", "Василий", "Дуся", "Ватрушка", "Бублик", "Мандарин", "Пирожок", "Клякса", "Шпрот", "Ромашка",
	"Облачко", "Тефтелька", "Кузя", "Муся", "Пряник", "Багира", "Чапа", "Лапочка", "Сэр Мурлок", "Граф Усатов",
	"Профессор Мяу", "Леди Пушистик", "Рыбкин", "Котофей", "Мурзик", "Буся", "Тиша", "Лютик",
	"Агата", "Алиса", "Бакс", "Беляш", "Бонифаций", "Боня", "Буран", "Ванилька", "Варежка", "Веснушка", "Вишенка", "Гарфилд", "Гоша", "Дымок", "Ёжик", "Жужа", "Звёздочка", "Златка", "Изюм", "Ирис", "Карамелька", "Каспер", "Кексик", "Клёпа", "Корица", "Кнопка", "Лаки", "Леопольд", "Лимончик", "Лолли", "Луиза", "Маффин", "Малыш", "Марс", "Мармелад", "Матроскин", "Мила", "Милка", "Мокко", "Моцарт", "Мурлыка", "Нюша", "Оливка", "Оскар", "Пирожок-младший", "Плюшка", "Пломбир", "Пуговка", "Пушинка", "Рафаэль", "Рокки", "Рыжуля", "Сахарок", "Светик", "Сёмга", "Сникерс", "Соус", "Стёпа", "Сырник", "Тайга", "Тигрёнок", "Тоффи", "Тостик", "Трюфель", "Тыковка", "Устрица", "Феликс", "Фиалка", "Фисташка", "Фрося", "Хвостик", "Хурма", "Цезарь", "Чарли", "Черничка", "Шарик", "Шоколадка", "Шустрик", "Эклер", "Юджин", "Ягодка", "Яшма", "Ватсон", "Шерлок", "Мистер Усы", "Миссис Мурр", "Капитан Лапка", "Доктор Мяу", "Барон Котовский", "Принцесса Пух", "Котлета", "Пельмешек", "Чизкейк", "Буррито", "Тако", "Начос", "Суши", "Ролл", "Васаби", "Мисо"]


static func def(t: String) -> Dictionary:
	return DEFS.get(t, {})


## Товары для производственных цепочек и цвет грузовика, который их возит.
const GOODS := {
	"fish": {"name": "Рыба", "col": "5fa8d3", "raw": true},
	"crop": {"name": "Урожай", "col": "8bc34a", "raw": true},
	"flour": {"name": "Мука", "col": "f1dfa6", "raw": true},
	"cotton": {"name": "Хлопок", "col": "f6f2e2", "raw": true},
}

## Кто что производит: [товар, из чего]. Цепочки короткие: поле или причал — склад — магазин.
const MAKES := {
	"pier": ["fish", []], "farm": ["crop", []], "wheat": ["flour", []], "cottonfield": ["cotton", []],
}

## Кому что привозить: с завезёнными товарами заведение зарабатывает больше (и готовит больше еды).
const USES := {
	"sushi": ["fish"], "restaurant": ["fish", "crop"], "market": ["fish", "crop"], "supermarket": ["fish", "crop", "flour"],
	"juicebar": ["crop"], "tacotruck": ["crop"], "icecream": ["crop"], "boba": ["crop"], "burger": ["flour", "crop"],
	"bakery": ["flour"], "pizzeria": ["flour"], "donut": ["flour"], "cafe": ["flour"],
	"factory": ["cotton"], "clothing": ["cotton"],
}


## Улучшения есть у всех построек, кроме дорог, природы, мелкого декора и чудес.
const NO_UPGRADE := ["road", "oneway", "boatdock", "highway", "path", "rail", "crossing", "flowers", "palm", "jacaranda", "wildpalm", "agave", "rock",
	"bench", "umbrella", "cushion", "lantern", "cattree", "statue", "billboard"]


static func ups(t: String) -> Array:
	var d: Dictionary = DEFS.get(t, {})
	if d.has("up"):
		return d.up
	if d.is_empty() or d.has("terra") or d.get("wonder", false) or NO_UPGRADE.has(t):
		return []
	var c := int(d.get("cost", 20))
	return [maxi(10, roundi(c * 0.6 / 5.0) * 5), maxi(20, roundi(c * 1.2 / 5.0) * 5)]


static func size_of(t: String) -> int:
	return int(DEFS.get(t, {}).get("size", 1))
