extends RefCounted
## Английский перевод: русская строка -> английская. Сгенерировано из таблицы перевода.

const EN := {
	"Котоград": "Kotograd",
	"Монетки": "Coins",
	"Еда для котиков": "Food for the cats",
	"Котики / мест в домах": "Cats / home spaces",
	"Работают / рабочих мест": "Working / jobs",
	"Счастье города": "City happiness",
	"Скорость времени (пробел)": "Game speed (Space)",
	"Включить / выключить музыку": "Music on / off",
	"Цели": "Goals",
	"Задания и достижения": "Quests and achievements",
	"Дзен": "Zen",
	"Режим «Дзен»: спрятать цели, подсказки и новости (Z)": "Zen mode: hide goals, hints and news (Z)",
	"Как играть": "How to play",
	"Меню": "Menu",
	"Звук": "Sound",
	"Тихо": "Quiet",
	"Пауза": "Pause",
	"Постройки ▴": "Buildings ▴",
	"Показать панель построек (V)": "Show the building panel (V)",
	"Скрыть ▾": "Hide ▾",
	"Спрятать панель построек и любоваться городом (V)": "Hide the building panel and admire the city (V)",
	"  ·  бесплатно": "  ·  free",
	"  ·  %d мон.": "  ·  %d coins",
	"Чудо света — можно построить только одно": "Wonder of the world — only one can be built",
	"Туристы: +%s мон./с": "Tourists: +%s coins/s",
	"Размер: 2×2": "Size: 2×2",
	"Жильцов: %d": "Residents: %d",
	"Рабочих мест: %d (%s)": "Jobs: %d (%s)",
	"Даёт еду": "Produces food",
	"Радость +%d в радиусе %d": "Joy +%d within radius %d",
	"Уют района +%d (радиус %d)": "Neighbourhood comfort +%d (radius %d)",
	"Приносит монетки": "Earns coins",
	"Служебная машина (нужна дорога)": "Service vehicle (needs a road)",
	"Стройка: %d с": "Construction: %d s",
	"Можно улучшить до уровня %d": "Can be upgraded to level %d",
	"Только на холмах и в горах": "Only on hills and mountains",
	"Хранилище монет +%d": "Coin storage +%d",
	"Хранилище еды +%d": "Food storage +%d",
	"Открывается при %d котиках": "Unlocks at %d cats",
	"нужно %d кот.": "needs %d cats",
	"построено": "built",
	"бесплатно": "free",
	"%d мон.": "%d coins",
	"Погладить": "Pet",
	"Улучшить": "Upgrade",
	"Улучшенное здание вмещает больше котиков, даёт больше монет и радости": "An upgraded building holds more cats and gives more coins and joy",
	"Не хватает монеток для улучшения": "Not enough coins for the upgrade",
	"%s котик · %s": "%s cat · %s",
	"Сейчас: ": "Now: ",
	"Работа: ": "Work: ",
	"Дом: ": "Home: ",
	"пока нет — ждёт новое жильё": "none yet — waiting for a new home",
	"ходит пешком": "walks on foot",
	"за рулём": "driving",
	"на парковке «%s»": "at the parking lot «%s»",
	"стоит прямо на дороге": "parked right on the road",
	"в гараже дома": "in the home garage",
	"Машина: ": "Car: ",
	"Настроение: ": "Mood: ",
	"Хочет кушать! Нужен рыбный причал или пекарня.": "Hungry! A fishing pier or a bakery is needed.",
	"Строится… %d%%": "Under construction… %d%%",
	"Чудо света": "Wonder of the world",
	"Уровень %d из %d": "Level %d of %d",
	"Туристы приносят +%s мон./с": "Tourists bring +%s coins/s",
	"Жильцы: %d/%d": "Residents: %d/%d",
	"  Скоро сюда кто-нибудь переедет…": "  Someone will move in soon…",
	"Уют: %d%%": "Comfort: %d%%",
	"Совет: дорога, тротуар, клумбы и городские службы рядом делают дом уютнее.": "Tip: a road, a sidewalk, flower beds and city services nearby make a home cosier.",
	"Работники: %d/%d (%s)": "Workers: %d/%d (%s)",
	" — на месте": " — at work",
	"  Ждём сотрудников — нужны новые жители.": "  Waiting for staff — new residents are needed.",
	"Подведите дорогу, чтобы выезжала служебная машина.": "Connect a road so the service vehicle can drive out.",
	"Машин: %d/%d": "Cars: %d/%d",
	"Подведите дорогу — иначе сюда не заехать.": "Connect a road — otherwise nobody can drive in.",
	"Радость: +%d домам в радиусе %d": "Joy: +%d to homes within radius %d",
	"Уют района: +%d в радиусе %d": "Neighbourhood comfort: +%d within radius %d",
	"Хранилище монет: +%d": "Coin storage: +%d",
	"Хранилище еды: +%d": "Food storage: +%d",
	"Улучшить до уровня %d — %s": "Upgrade to level %d — %s",
	"на седьмом небе": "in seventh heaven",
	"счастливое": "happy",
	"спокойное": "calm",
	"скучает": "bored",
	"грустное": "sad",
	"Добро пожаловать в Котоград!": "Welcome to Kotograd!",
	"На солнечном калифорнийском побережье всегда хорошая погода. Постройте настоящий город, где котики живут, работают и отдыхают!": "The sunny California coast always has good weather. Build a real city where cats live, work and relax!",
	"• Рельеф — начинаем на небольшом островке. Насыпайте землю и песок, а инструментом «Вода» убирайте сушу. Это бесплатно!": "• Terrain — we start on a small island. Add land and sand, and remove land with the «Water» tool. It is free!",
	"• Жильё — домики, коттеджи, виллы и многоэтажки. Сколько мест в домах — столько котиков в городе.": "• Housing — little houses, cottages, villas and apartment blocks. The more home spaces, the more cats in the city.",
	"• Работа и бизнес — котики сами устраиваются на работу и надевают форму: блогеры, разработчики в худи, актёры, серферы, строители в касках…": "• Work and business — cats find jobs on their own and wear uniforms: bloggers, developers in hoodies, actors, surfers, builders in hard hats…",
	"• Город — мэрия, школа, больница, полиция, почта. Делают районы уютнее, а их машины разъезжают по улицам.": "• City — city hall, school, hospital, police, post office. They make neighbourhoods cosier, and their vehicles drive around the streets.",
	"• Дороги — двусторонние, по ним котики утром едут на работу, а вечером домой. Дом и работа должны стоять у дороги. Пешком котики ходят по тротуарам и только переходят дорогу.": "• Roads — two-way; cats drive to work in the morning and home in the evening. Homes and workplaces must stand next to a road. On foot, cats walk on sidewalks and only cross roads.",
	"• Магистраль — по 2 полосы в каждую сторону: быстро и с обгонами. Здания к ней не подключаются: подведите обычную дорогу вплотную — на стыке появится съезд с зелёным указателем.": "• Highway — 2 lanes each way: fast, with overtaking. Buildings do not connect to it: bring a regular road right up to it — an on-ramp with a green sign appears at the junction.",
	"• Перекрёстки — где сходятся 3–4 дороги, сами появляются светофоры и пешеходные зебры: машины ждут зелёного, а котики переходят по зебре.": "• Intersections — where 3–4 roads meet, traffic lights and zebra crossings appear by themselves: cars wait for green, and cats cross at the zebra.",
	"• Поезда — проложите рельсы и поставьте вплотную к ним вокзал или платформу (минимум две). Поезд будет ходить сам, а котики — ездить в другие районы. Рельсы через дорогу — переезд со шлагбаумом.": "• Trains — lay rails and place a station or platform right next to them (at least two). The train runs by itself, and cats ride it to other districts. Rails across a road make a level crossing with a barrier.",
	"• Аэропорты — если их хотя бы два, котики летают между ними. Удобно для дальних островов.": "• Airports — if there are at least two, cats fly between them. Handy for distant islands.",
	"• Холмы и горы — дома с видом уютнее, а особняки строятся только наверху.": "• Hills and mountains — homes with a view are cosier, and mansions are built only up there.",
	"• Улучшения — нажмите на здание: многие можно улучшить до 3 уровня — здание станет выше и наряднее.": "• Upgrades — click a building: most can be upgraded to level 3, and the building gets taller and fancier.",
	"• Лимиты — монеты и еда копятся до предела хранилищ: банки, склады и супермаркеты поднимают его.": "• Limits — coins and food pile up to the storage limit: banks, warehouses and supermarkets raise it.",
	"• Парковки — котики оставляют на них машины. Если парковки рядом нет, машину бросают прямо на дороге, и начинаются пробки!": "• Parking — cats leave their cars there. If there is no parking nearby, they leave the car right on the road and traffic jams begin!",
	"• Еда — рыбные причалы и пекарни. Отдых и природа — пляжи, пальмы, зонтики, фонтаны и знак KOTOWOOD.": "• Food — fishing piers and bakeries. Leisure and nature — beaches, palms, umbrellas, fountains and the KOTOWOOD sign.",
	"• Чудеса — достопримечательности Лос-Анджелеса: обсерватория, пирс с колесом обозрения, стадион… Каждое строится один раз и привлекает туристов.": "• Wonders — Los Angeles landmarks: the observatory, the pier with a Ferris wheel, the stadium… Each is built once and attracts tourists.",
	"• Если снести дом, котики не пропадут: погуляют и переедут, как только появится новое жильё.": "• If you demolish a house, the cats will not disappear: they will stroll around and move in as soon as a new home appears.",
	"• Цели — слева сверху текущее задание, за каждое дают монетки. Все задания и достижения — кнопка «Цели».": "• Goals — the current quest is at the top left, and each one gives coins. All quests and achievements are under the «Goals» button.",
	"• События — иногда в городе праздник: фестиваль на пляже, ярмарка, премьера, салют. Гости приходят сами, а котики становятся счастливее.": "• Events — sometimes the city celebrates: a beach festival, a farmers market, a premiere, fireworks. Guests come by themselves, and the cats get happier.",
	"ЛКМ — строить (дороги можно вести мышью) · ПКМ / перетаскивание — двигать карту": "LMB — build (roads can be drawn with the mouse) · RMB / drag — move the map",
	"Колесо — масштаб · WASD — камера · Tab — вкладки · 1–9 — постройки · B — лопатка": "Wheel — zoom · WASD — camera · Tab — tabs · 1–9 — buildings · B — shovel",
	"Рельеф, дороги и клумбы можно «рисовать», ведя мышью с зажатой кнопкой": "Terrain, roads and flower beds can be «painted» by dragging with the button held",
	"Клик по котику или машине — узнать, кто это · Пробел — скорость · Z — режим «Дзен» · V — спрятать постройки · Esc — отмена": "Click a cat or a car to see who it is · Space — speed · Z — Zen mode · V — hide buildings · Esc — cancel",
	"На телефоне: касание — строить или выбрать · один палец — двигать карту · два пальца — масштаб": "On a phone: tap — build or select · one finger — move the map · two fingers — zoom",
	"Мяу, начинаем!": "Meow, let's begin!",
	"Город сохраняется автоматически.": "The city is saved automatically.",
	"Продолжить": "Continue",
	"Настройки": "Settings",
	"Главное меню": "Main menu",
	"Новый город": "New city",
	"Выйти из игры": "Quit game",
	"Город сохранится автоматически": "The city will be saved automatically",
	"Точно? Нажмите ещё раз": "Sure? Click again",
	"Новый остров ждёт котиков!": "A new island is waiting for cats!",
	"Язык · Language": "Language · Язык",
	"Разрешение окна": "Window resolution",
	"Во весь экран": "Fullscreen",
	"Экран": "Screen",
	"Масштаб интерфейса": "Interface scale",
	"Музыка": "Music",
	"Трек": "Track",
	"Звуки": "Sounds",
	"Окружение": "Ambience",
	"Неограниченные ресурсы": "Unlimited resources",
	"Строить и улучшать всё бесплатно, без ожидания котиков. Котики всё равно переезжают постепенно.": "Build and upgrade everything for free, without waiting for cats. Cats still move in gradually.",
	"Режим игры": "Game mode",
	"Режим «Дзен»": "Zen mode",
	"Только город, музыка и стройка: без целей, подсказок и новостей. Цели всё равно засчитываются тихо.": "Just the city, music and building: no goals, hints or news. Goals still count quietly.",
	"Масштаб карты — колёсико мыши, клавиши − и + или два пальца на телефоне.": "Map zoom — mouse wheel, the − and + keys, or two fingers on a phone.",
	"Сохранения": "Saves",
	"Экспорт в файл…": "Export to file…",
	"Сохранить город в файл .json — например, чтобы перенести на другой компьютер": "Save the city to a .json file — for example, to move it to another computer",
	"Импорт из файла…": "Import from file…",
	"Загрузить город из файла .json. Текущий город будет заменён.": "Load a city from a .json file. The current city will be replaced.",
	"Готово": "Done",
	"*.json ; Сохранение Котограда": "*.json ; Kotograd save",
	"Город скачан: ": "City downloaded: ",
	"Не получилось сохранить файл": "Could not save the file",
	"Город сохранён: ": "City saved: ",
	"Этот файл не похож на сохранение Котограда": "This file does not look like a Kotograd save",
	"Город загружен: ": "City loaded: ",
	"Неограниченные ресурсы: ": "Unlimited resources: ",
	"включены": "on",
	"выключены": "off",
	"+%.1f/с": "+%.1f/s",
	"%s%.1f/с": "%s%.1f/s",
	"День %d · %02d:%02d": "Day %d · %02d:%02d",
	"Начнём! Во вкладке «Жильё» постройте Домик, а во вкладке «Рельеф» можно бесплатно расширять остров.": "Let's begin! Build a Little house in the «Housing» tab, and you can expand the island for free in the «Terrain» tab.",
	"Котик уже собирает чемодан и скоро приедет…": "A cat is already packing a suitcase and will arrive soon…",
	"Котиков без дома: %d. Постройте жильё — они сразу переедут!": "Homeless cats: %d. Build housing — they will move in right away!",
	"Подсказка: котикам нужна работа! Поставьте Рыбный причал у воды (вкладка «Еда»).": "Tip: the cats need jobs! Place a Fishing pier by the water («Food» tab).",
	"Еда закончилась! Нужен ещё один рыбный причал или пекарня.": "Out of food! Another fishing pier or bakery is needed.",
	"Подсказка: проложите Дорогу мимо домов и работы — котики поедут на машинах!": "Tip: lay a Road past the homes and workplaces — the cats will drive cars!",
	"Все дома заняты — постройте ещё жильё, чтобы приехали новые котики.": "All homes are full — build more housing so new cats can arrive.",
	"Не всем хватает работы — постройте магазин, пекарню или городские службы.": "Not everyone has a job — build a shop, a bakery or city services.",
	"Хранилище монет заполнено! Потратьте монетки или постройте Банк (вкладка «Бизнес»).": "Coin storage is full! Spend some coins or build a Bank («Business» tab).",
	"Склады еды полны — постройте Склад или Супермаркет, чтобы запасать больше.": "Food storage is full — build a Warehouse or a Supermarket to store more.",
	"Машины стоят прямо на дорогах — бывают пробки! Постройте Парковку рядом с работой и магазинами.": "Cars are parked right on the roads — traffic jams happen! Build a Parking lot near workplaces and shops.",
	"Котикам скучновато: украсьте город клумбами и деревьями рядом с домами.": "The cats are a bit bored: decorate the city with flower beds and trees near the homes.",
	"Нажмите, чтобы увидеть все цели и достижения": "Click to see all goals and achievements",
	"Показать": "Show",
	"Перенести камеру к празднику": "Move the camera to the celebration",
	"Все задания выполнены!": "All quests completed!",
	"Город стал легендой. Стройте дальше в своё удовольствие.": "The city has become a legend. Keep building for your own pleasure.",
	"Праздник: %s\nещё %d ч.": "Celebration: %s\n%d h left",
	"Выполнено целей и достижений: %d!%s": "Goals and achievements completed: %d!%s",
	"  +%d мон.": "  +%d coins",
	"Цель выполнена: «%s»%s": "Goal completed: «%s»%s",
	"Достижение: «%s» — %s": "Achievement: «%s» — %s",
	"Цели и достижения": "Goals and achievements",
	"Закрыть": "Close",
	"готово": "done",
	"\n+%d мон.": "\n+%d coins",
	"Задания: %d из %d": "Quests: %d of %d",
	"Достижения: %d из %d": "Achievements: %d of %d",
	"Город-легенда!": "Legendary city!",
	"Все чудеса света построены, и о вашем городе знает всё побережье. Котики устраивают в вашу честь большой салют!\n\nВсе задания выполнены, но город можно строить и дальше: ищите новые достижения и праздники.": "All the wonders of the world are built, and the whole coast knows about your city. The cats are throwing a big fireworks show in your honour!\n\nAll quests are done, but you can keep building: look for new achievements and celebrations.",
	"Ура!": "Hooray!",
	"%s закончился — котики довольны!": "%s is over — the cats are happy!",
	"Праздник «%s» закончился — котики довольны!": "The «%s» celebration is over — the cats are happy!",
	"Режим «Дзен»: только город, музыка и стройка": "Zen mode: just the city, music and building",
	"Режим «Дзен» выключен: цели и подсказки снова на месте": "Zen mode off: goals and hints are back",
	"Сейчас играет: %s": "Now playing: %s",
	"%s — уровень %d!": "%s — level %d!",
	"%s нашёл новый дом!": "%s found a new home!",
	"%s переезжает в %s!": "%s is moving to %s!",
	"Открыто: %s!": "Unlocked: %s!",
	"Ищет работу": "Looking for a job",
	"мрр... zZ": "purr... zZ",
	"Мурр!": "Purr!",
	"Мяу!": "Meow!",
	"Мрр~": "Mrrr~",
	"домой": "home",
	"на работу": "to work",
	"в «%s»": "to «%s»",
	"гулять": "for a walk",
	"летит на самолёте": "flying on a plane",
	"едет на поезде": "riding a train",
	"едет %s на машине": "driving %s",
	"идёт %s": "walking %s",
	"гуляет": "strolling",
	"ждёт %s в «%s»": "waiting for a %s at «%s»",
	"самолёт": "plane",
	"поезд": "train",
	"спит дома": "sleeping at home",
	"отдыхает дома": "resting at home",
	"работает": "working",
	"дремлет под открытым небом": "napping under the open sky",
	"дремлет": "napping",
	"ждёт новый дом": "waiting for a new home",
	"отдыхает на улице": "relaxing outside",
	"Би-бип!": "Beep-beep!",
	"Пока закрыто": "Locked for now",
	"Сначала уберите постройку": "Remove the building first",
	"Ставьте вплотную к рельсам": "Place it right next to the rails",
	"Это чудо уже есть в городе": "This wonder is already in the city",
	"Не помещается": "Does not fit",
	"Здесь занято": "Occupied",
	"Строится только на холмах и в горах": "Can only be built on hills and mountains",
	"Слишком круто: в горах — только жильё и дороги": "Too steep: only housing and roads in the mountains",
	"Нельзя на воде": "Not on water",
	"Нужна вода рядом": "Needs water nearby",
	"Не хватает монеток": "Not enough coins",
	"Нужно 2 монетки": "Need 2 coins",
	"%s остался без дома и ждёт новый": "%s lost their home and is waiting for a new one",
	"%s — готово!": "%s — done!",
	"Чудо света построено: %s! Туристы уже едут.": "Wonder of the world built: %s! Tourists are on their way.",
	"Доброе утро! Начинается день %d": "Good morning! Day %d begins",
	"«%s» откроется, когда в городе будет %d котиков": "«%s» unlocks when the city has %d cats",
	"Санта-Мурика": "Santa Murica",
	"Мурбелла-Бич": "Murbella Beach",
	"Лос-Котос": "Los Catos",
	"Мяу-Бэй": "Meow Bay",
	"Мурлибу": "Murlibu",
	"Кошачья Бухта": "Kitty Cove",
	"Санта-Кэтлина": "Santa Catlina",
	"Пальм-Котингс": "Palm Catings",
	"Котосвилл": "Catsville",
	"Мурсайд": "Purrside",
	"Лапа-Верде": "Paw Verde",
	"Выйти": "Quit",
	"Как назовём город?": "What shall we call the city?",
	"Другое": "Another",
	"Придумать другое название": "Suggest another name",
	"Назад": "Back",
	"Основать город!": "Found the city!",
	"Вся графика и музыка нарисованы кодом · сделано с любовью к котикам": "All graphics and music are drawn with code · made with love for cats",
	"уютный город для котиков у океана": "a cosy city for cats by the ocean",
	"Продолжить: %s": "Continue: %s",
	"Город «%s» будет заменён новым островом.": "The city «%s» will be replaced by a new island.",
	"Добро пожаловать в %s!": "Welcome to %s!",
	"Фестиваль на пляже": "Beach festival",
	"Музыка, мороженое и серфинг — все на пляж!": "Music, ice cream and surfing — everyone to the beach!",
	"Салют над океаном": "Fireworks over the ocean",
	"Сегодня вечером праздничный салют — посмотрите на небо!": "Fireworks tonight — look up at the sky!",
	"Фермерская ярмарка": "Farmers market",
	"Овощи, мёд и кошачья мята прямо с грядки.": "Vegetables, honey and catnip fresh from the garden.",
	"Кинопремьера": "Movie premiere",
	"Красная дорожка, звёзды в тёмных очках и вспышки камер!": "A red carpet, stars in sunglasses and camera flashes!",
	"Матч «Котоджерс»": "The Catdgers game",
	"Бейсбол, хот-доги и волна на трибунах!": "Baseball, hot dogs and the wave in the stands!",
	"Автобус туристов": "Tour bus",
	"Туристы приехали посмотреть на чудо света и привезли монетки.": "Tourists came to see the wonder of the world and brought coins.",
	"Хоум-ран!": "Home run!",
	"Мяу-у!": "Meow-ow!",
	"Первый домик": "First little house",
	"Постройте Домик во вкладке «Жильё»": "Build a Little house in the «Housing» tab",
	"Новосёлы": "Housewarming",
	"Дождитесь первого жителя": "Wait for the first resident",
	"Дорога домой": "The road home",
	"Проложите 10 клеток дороги": "Lay 10 tiles of road",
	"Рыбный день": "Fish day",
	"Еды должно производиться больше, чем съедается: поставьте причал или ферму": "Produce more food than the cats eat: place a pier or a farm",
	"Первая смена": "First shift",
	"Устройте на работу 5 котиков": "Give jobs to 5 cats",
	"Дружная улица": "Friendly street",
	"Поселите 10 котиков": "Settle 10 cats",
	"Шопинг": "Shopping",
	"Откройте 3 магазина или кафе": "Open 3 shops or cafes",
	"Зелёный район": "Green neighbourhood",
	"Поставьте 10 украшений: пальмы, клумбы, скамейки, фонтаны…": "Place 10 decorations: palms, flower beds, benches, fountains…",
	"Где припарковаться?": "Where to park?",
	"Постройте парковку или паркинг": "Build a parking lot or a parking garage",
	"Городские службы": "City services",
	"Постройте 2 городские службы: школу, больницу, полицию…": "Build 2 city services: a school, a hospital, police…",
	"Счастливый город": "Happy city",
	"Поднимите счастье города до 65%": "Raise city happiness to 65%",
	"Городок": "Small town",
	"Поселите 30 котиков": "Settle 30 cats",
	"Капремонт": "Renovation",
	"Улучшите любое здание: нажмите на него и выберите «Улучшить»": "Upgrade any building: click it and choose «Upgrade»",
	"Дом с видом": "House with a view",
	"Постройте жильё на холме или в горах": "Build housing on a hill or in the mountains",
	"Деловой квартал": "Business district",
	"Создайте 60 рабочих мест": "Create 60 jobs",
	"Фривей": "Freeway",
	"Проложите 15 клеток магистрали": "Lay 15 tiles of highway",
	"Постройте первое чудо из вкладки «Чудеса»": "Build the first wonder from the «Wonders» tab",
	"Настоящий город": "A real city",
	"Поселите 60 котиков": "Settle 60 cats",
	"Шедевр архитектуры": "Architectural masterpiece",
	"Улучшите здание до 3 уровня": "Upgrade a building to level 3",
	"Туристическая мекка": "Tourist hotspot",
	"Привлеките туристов: доход от туризма 10 в секунду": "Attract tourists: tourism income of 10 per second",
	"Мегаполис": "Metropolis",
	"Поселите 100 котиков": "Settle 100 cats",
	"Город-легенда": "Legendary city",
	"Постройте все 11 чудес света": "Build all 11 wonders of the world",
	"Мур-мур": "Purr-purr",
	"Погладьте 10 котиков": "Pet 10 cats",
	"Главный по почесушкам": "Chief of chin scratches",
	"Погладьте 100 котиков": "Pet 100 cats",
	"Неделя у океана": "A week by the ocean",
	"Проживите в городе 7 дней": "Live in the city for 7 days",
	"Старожил": "Old-timer",
	"Проживите в городе 30 дней": "Live in the city for 30 days",
	"Архипелаг": "Archipelago",
	"Расширьте сушу до 700 клеток": "Expand the land to 700 tiles",
	"Пробка на 405-й": "Jam on the 405",
	"Соберите настоящую пробку из 6 машин": "Make a real traffic jam of 6 cars",
	"Котокапиталист": "Cat capitalist",
	"Накопите 10 000 монеток": "Save up 10,000 coins",
	"Всего понемногу": "A bit of everything",
	"Постройте 25 разных видов зданий": "Build 25 different kinds of buildings",
	"Город всего на свете": "A city of everything",
	"Постройте 60 разных видов зданий": "Build 60 different kinds of buildings",
	"Праздник!": "Party time!",
	"Проведите первое городское событие": "Hold the first city event",
	"Душа компании": "Life of the party",
	"Проведите 10 городских событий": "Hold 10 city events",
	"Сияющий город": "Shining city",
	"Улучшите 10 зданий до 3 уровня": "Upgrade 10 buildings to level 3",
	"На седьмом небе": "In seventh heaven",
	"Счастье города 90%": "City happiness at 90%",
	"Чух-чух!": "Choo-choo!",
	"Соедините рельсами две станции, чтобы пошёл поезд": "Connect two stations with rails so a train starts running",
	"Рейс по расписанию": "Scheduled flight",
	"Постройте два аэропорта": "Build two airports",
	"Час пик": "Rush hour",
	"Котики совершили 50 поездок на поезде и самолёте": "Cats made 50 trips by train and plane",
	"Котополис": "Catopolis",
	"Поселите 200 котиков": "Settle 200 cats",
	"Авто: по времени суток": "Auto: by time of day",
	"Котоград — дневной грув": "Kotograd — daytime groove",
	"Санта-Мурика Бич": "Santa Murica Beach",
	"Сансет-бульвар": "Sunset Boulevard",
	"Ленивое воскресенье": "Lazy Sunday",
	"Мурлибу на рассвете": "Murlibu at dawn",
	"Все треки по кругу": "All tracks in a loop",
	"Земля": "Land",
	"Насыпать землю на воду или песок. Бесплатно — расширяйте остров!": "Add land on water or sand. Free — expand the island!",
	"Песок": "Sand",
	"Насыпать песок — получится пляж. Бесплатно.": "Add sand to make a beach. Free.",
	"Холм": "Hill",
	"Насыпать холм. На холмах можно строить, а дома оттуда с видом — уютнее. Бесплатно.": "Raise a hill. You can build on hills, and homes with a view are cosier. Free.",
	"Горы": "Mountains",
	"Поднять горы. В горах строят только жильё, дороги и украшения. Бесплатно.": "Raise mountains. Only housing, roads and decorations can be built there. Free.",
	"Сухая трава": "Dry grass",
	"Калифорнийская сухая трава и кустарник. Бесплатно.": "California dry grass and shrubs. Free.",
	"Луг": "Meadow",
	"Цветущий луг с маками. Бесплатно.": "A blooming meadow with poppies. Free.",
	"Вода": "Water",
	"Убрать сушу: здесь снова будет вода. Бесплатно. Под дорогой получится мост.": "Remove land: there will be water here again. Free. Under a road it becomes a bridge.",
	"Дорога (2 полосы)": "Road (2 lanes)",
	"По дорогам котики ездят на машинах на работу и домой. На воде получается мост (8 мон.).": "Cats drive along roads to work and home. On water it becomes a bridge (8 coins).",
	"Парковка": "Parking lot",
	"Стоянка на 4 машины у дороги. Котики оставляют здесь машины и идут пешком. Без парковок машины стоят прямо на дорогах — бывают пробки!": "A lot for 4 cars by the road. Cats leave their cars here and walk. Without parking, cars stand right on the roads — traffic jams happen!",
	"Паркинг": "Parking garage",
	"Многоэтажный паркинг на 20 машин. Ставьте рядом с офисами и чудесами.": "A multi-storey garage for 20 cars. Place it near offices and wonders.",
	"Магистраль": "Highway",
	"Широкое шоссе: по 2 полосы в каждую сторону, машины едут быстрее и обгоняют. Пешеходам сюда нельзя. Дома к магистрали не подключаются — нужна обычная дорога.": "A wide freeway: 2 lanes each way, cars go faster and overtake. No pedestrians. Homes do not connect to the highway — a regular road is needed.",
	"Железная дорога": "Railway",
	"Рельсы для поездов. Поезд сам ходит между вокзалами и платформами одной линии, а котики ездят на нём в другие районы. Через дорогу получится переезд со шлагбаумом, через воду — мост.": "Rails for trains. A train runs by itself between the stations and platforms of one line, and cats ride it to other districts. Across a road it becomes a level crossing with a barrier, across water a bridge.",
	"Железнодорожный переезд": "Level crossing",
	"Когда идёт поезд, шлагбаум закрывается и машины ждут.": "When a train passes, the barrier closes and the cars wait.",
	"Платформа": "Platform",
	"Маленькая остановка поезда. Ставьте вплотную к рельсам.": "A small train stop. Place it right next to the rails.",
	"Вокзал «Юнион»": "Union Station",
	"Большой вокзал с часовой башней. Ставьте вплотную к рельсам — поезд будет останавливаться здесь.": "A big station with a clock tower. Place it right next to the rails — the train will stop here.",
	"Аэропорт": "Airport",
	"Самолёты летают в другие аэропорты вашего города. Нужно хотя бы два аэропорта — иначе лететь некуда. Отлично связывает дальние острова!": "Planes fly to the other airports of your city. You need at least two airports — otherwise there is nowhere to fly. Great for connecting distant islands!",
	"Тротуар": "Sidewalk",
	"Пешеходная дорожка: по ней котики ходят быстрее.": "A footpath: cats walk faster on it.",
	"Домик": "Little house",
	"Домик с ушками на крыше. Живут 3 котика.": "A little house with ears on the roof. 3 cats live here.",
	"Коттедж": "Cottage",
	"Большой семейный дом с садиком. Живут 5 котиков.": "A big family house with a little garden. 5 cats live here.",
	"Вилла с бассейном": "Villa with a pool",
	"Белая вилла в калифорнийском стиле. Бассейн, шезлонги и вид на океан.": "A white California-style villa. A pool, sun loungers and an ocean view.",
	"Многоэтажка": "Apartment block",
	"Многоквартирный дом с балкончиками. Живут 11 котиков.": "An apartment building with little balconies. 11 cats live here.",
	"Рыбный причал": "Fishing pier",
	"Ставится у воды. Рыбаки ловят рыбку для всего города.": "Placed by the water. Fishers catch fish for the whole city.",
	"Магазин": "Shop",
	"Магазин клубков и всякой всячины. Котики заходят за покупками.": "A shop of yarn balls and odds and ends. Cats drop in for shopping.",
	"Киоск мороженого": "Ice cream kiosk",
	"Рыбное мороженое в вафельном рожке — хит пляжного сезона.": "Fish ice cream in a waffle cone — the hit of beach season.",
	"Пекарня": "Bakery",
	"Свежие рыбные пирожки каждое утро.": "Fresh fish pies every morning.",
	"Суши-бар": "Sushi bar",
	"Роллы с лососем и тунцом — котики в восторге.": "Salmon and tuna rolls — the cats are delighted.",
	"Пиццерия": "Pizzeria",
	"Пицца «Четыре рыбки» прямо из печи.": "«Four Fishes» pizza straight from the oven.",
	"Груминг-салон": "Grooming salon",
	"Стрижка, расчёсывание и бантики. После салона котики сияют!": "Haircuts, brushing and bows. After the salon the cats shine!",
	"Котокафе": "Cat cafe",
	"Молочный латте и пирожные. Любимое место встреч.": "Milky lattes and pastries. Everyone's favourite meeting place.",
	"Фитнес-клуб": "Fitness club",
	"Котики качают лапки и бегают на дорожке за лазерной точкой.": "Cats work out their paws and run on the treadmill after a laser dot.",
	"Кинотеатр": "Cinema",
	"Премьеры, попкорн и огни над входом.": "Premieres, popcorn and lights over the entrance.",
	"Блог-студия": "Blog studio",
	"Здесь снимают ролики «Мой день в Котограде». Лайк, подписка, мур!": "This is where they film «My day in Kotograd». Like, subscribe, purr!",
	"Ферма": "Farm",
	"Грядки с кошачьей мятой и огород. Много еды для города.": "Catnip beds and a vegetable garden. Lots of food for the city.",
	"Стройконтора": "Construction office",
	"Строители в касках. С ними все стройки идут быстрее!": "Builders in hard hats. With them, all construction goes faster!",
	"Айти-компания": "IT company",
	"Разработчики в худи пишут код и пьют молочный раф. Стартап «Мяугл».": "Developers in hoodies write code and drink milky lattes. The «Meowgle» startup.",
	"Офис": "Office",
	"Котики в пиджаках и галстуках перекладывают важные бумажки.": "Cats in suits and ties shuffle important papers.",
	"Биржа": "Stock exchange",
	"Трейдеры следят за котировками рыбы и клубков. Акции только растут!": "Traders watch the prices of fish and yarn. Stocks only go up!",
	"Киностудия": "Film studio",
	"Здесь снимают блокбастеры про котиков. Звёзды в тёмных очках!": "Blockbusters about cats are filmed here. Stars in sunglasses!",
	"Фабрика клубков": "Yarn factory",
	"Здесь сматывают клубочки для всего острова.": "Yarn balls are wound here for the whole island.",
	"Мэрия": "City hall",
	"Сердце города. Здесь мэр и чиновники решают важные кошачьи вопросы.": "The heart of the city. The mayor and officials settle important cat matters here.",
	"Спасательная вышка": "Lifeguard tower",
	"Спасатель в красных шортах следит за пляжем.": "A lifeguard in red shorts watches over the beach.",
	"Почта": "Post office",
	"Почтальоны развозят письма и посылки.": "Mail carriers deliver letters and parcels.",
	"Школа": "School",
	"Учителя в очках учат котят считать рыбок.": "Teachers in glasses teach kittens to count fish.",
	"Полиция": "Police",
	"Полицейские патрулируют улицы на машине с мигалкой.": "Police officers patrol the streets in a car with a siren.",
	"Больница": "Hospital",
	"Добрые доктора в белых халатах. Иногда выезжает скорая.": "Kind doctors in white coats. Sometimes the ambulance drives out.",
	"Пожарная часть": "Fire station",
	"Отважные пожарные (и котиков с пальм снимают!).": "Brave firefighters (they even get cats down from palm trees!).",
	"Библиотека": "Library",
	"Тихое место, где котики читают книжки про рыбалку.": "A quiet place where cats read books about fishing.",
	"Серф-школа": "Surf school",
	"Ставится у воды. Инструкторы учат котиков ловить волну.": "Placed by the water. Instructors teach cats to catch a wave.",
	"Клумба": "Flower bed",
	"Цветочки радуют соседей.": "Flowers cheer up the neighbours.",
	"Пальма": "Palm tree",
	"Высокая калифорнийская пальма.": "A tall California palm.",
	"Пляжный зонтик": "Beach umbrella",
	"Зонтик и полотенце — можно позагорать.": "An umbrella and a towel — time to sunbathe.",
	"Скамейка": "Bench",
	"Можно присесть и посмотреть на прохожих.": "Sit down and watch the passers-by.",
	"Жакаранда": "Jacaranda",
	"Сиреневое дерево Лос-Анджелеса, с которого летят лепестки.": "The purple tree of Los Angeles that drops its petals.",
	"Лежанка": "Cat bed",
	"Мягкая подушка, чтобы вздремнуть.": "A soft cushion for a nap.",
	"Фонарь": "Street lamp",
	"Тёплый свет по вечерам.": "Warm light in the evenings.",
	"Когтеточка": "Scratching post",
	"Можно точить когти и лазать по полочкам!": "Sharpen your claws and climb the shelves!",
	"Фонтан": "Fountain",
	"Журчащая вода — можно смотреть вечно.": "Babbling water — you could watch it forever.",
	"Детская площадка": "Playground",
	"Качели, горка и песочница.": "Swings, a slide and a sandbox.",
	"Памятник": "Monument",
	"Памятник Первому Коту — основателю города.": "A monument to the First Cat — founder of the city.",
	"Знак «KOTOWOOD»": "KOTOWOOD sign",
	"Огромные буквы на холме — символ города. Все туристы фотографируются!": "Giant letters on the hill — the symbol of the city. Every tourist takes a photo!",
	"Пирс Санта-Мурики": "Santa Murica Pier",
	"Колесо обозрения и аттракционы прямо над океаном. Ставится у воды.": "A Ferris wheel and rides right over the ocean. Placed by the water.",
	"Обсерватория Гриффит": "Griffith Observatory",
	"Белые купола на холме. Отсюда котики смотрят на звёзды и огни города.": "White domes on the hill. From here the cats watch the stars and the city lights.",
	"Концертный зал Диснейя": "Disnea Concert Hall",
	"Серебряные паруса из стали. Здесь играет кошачий симфонический оркестр.": "Silver sails of steel. The feline symphony orchestra plays here.",
	"Стадион «Котоджерс»": "Catdgers Stadium",
	"Бейсбол, хот-доги и волна на трибунах. Весь город болеет за своих!": "Baseball, hot dogs and the wave in the stands. The whole city cheers for the home team!",
	"Кошачья башня": "Cat Tower",
	"Величайшая когтеточка мира — гордость Котограда!": "The greatest scratching post in the world — the pride of Kotograd!",
	"Трейлер": "Trailer",
	"Серебристый трейлер с гирляндой. Живёт 1 котик.": "A silver trailer with fairy lights. 1 cat lives here.",
	"Пляжное бунгало": "Beach bungalow",
	"Домик на пляже с верандой. Живут 2 котика.": "A beach house with a porch. 2 cats live here.",
	"Таунхаус": "Townhouse",
	"Узкие разноцветные дома в ряд. Живут 3 котика.": "Narrow colourful houses in a row. 3 cats live here.",
	"Особняк на холмах": "Hillside mansion",
	"Роскошный особняк с видом на город. Строится только на холмах и в горах! Живут 4 котика.": "A luxurious mansion with a view of the city. Built only on hills and mountains! 4 cats live here.",
	"Жилая башня": "Residential tower",
	"Стеклянный небоскрёб в Даунтауне. Живут 16 котиков.": "A glass skyscraper in Downtown. 16 cats live here.",
	"Магазин техники": "Electronics store",
	"Ноутбуки, телефоны и игровые приставки.": "Laptops, phones and game consoles.",
	"Бутик": "Boutique",
	"Модная одежда с Родео-драйв.": "Fashionable clothes from Rodeo Drive.",
	"Книжный магазин": "Bookstore",
	"Книги, комиксы и уютное кресло.": "Books, comics and a cosy armchair.",
	"Магазин игрушек": "Toy store",
	"Мячики, мышки и лазерные указки.": "Balls, toy mice and laser pointers.",
	"Зоомагазин": "Pet shop",
	"Корм, лежанки и рыбки в аквариумах.": "Food, beds and fish in aquariums.",
	"Цветочный магазин": "Flower shop",
	"Букеты из кошачьей мяты.": "Catnip bouquets.",
	"Аптека": "Pharmacy",
	"Витамины для шерсти и пластыри для лапок.": "Vitamins for fur and plasters for paws.",
	"Супермаркет": "Supermarket",
	"Огромный магазин: еда и всё для дома. Хранит много еды.": "A huge store: food and everything for the home. Stores a lot of food.",
	"Торговый центр": "Shopping mall",
	"Десятки магазинов под одной крышей.": "Dozens of shops under one roof.",
	"Бургерная": "Burger joint",
	"Рыбные бургеры In-N-Mur.": "In-N-Mur fish burgers.",
	"Тако-фургон": "Taco truck",
	"Тако с рыбкой прямо с колёс!": "Fish tacos straight off the wheels!",
	"Пончиковая": "Donut shop",
	"Огромный пончик на крыше — как в Лос-Анджелесе!": "A giant donut on the roof — just like in Los Angeles!",
	"Бабл-ти": "Bubble tea",
	"Молочный чай с шариками тапиоки.": "Milk tea with tapioca pearls.",
	"Фреш-бар": "Juice bar",
	"Смузи из авокадо — очень по-калифорнийски.": "Avocado smoothies — very Californian.",
	"Ресторан": "Restaurant",
	"Ужин при свечах с видом на закат.": "Candlelit dinner with a sunset view.",
	"Фермерский рынок": "Farmers' market",
	"Овощи, фрукты и свежая рыба под навесами.": "Vegetables, fruit and fresh fish under the awnings.",
	"Барбершоп": "Barbershop",
	"Стрижка усов и бороды.": "Whisker and beard trims.",
	"Спа-салон": "Spa",
	"Массаж лапок и ванны с ромашкой.": "Paw massages and chamomile baths.",
	"Йога-студия": "Yoga studio",
	"Поза «потягивающийся котик».": "The «stretching cat» pose.",
	"Тату-салон": "Tattoo parlour",
	"Татуировки с рыбками и сердечками.": "Tattoos with little fish and hearts.",
	"Стоматология": "Dentist",
	"Чистка клыков без страха.": "Fang cleaning without fear.",
	"Ветклиника": "Vet clinic",
	"Прививки и витаминки для котиков.": "Vaccines and vitamins for cats.",
	"Прачечная": "Laundromat",
	"Стирка плюшевых пледов.": "Washing fluffy blankets.",
	"Заправка": "Gas station",
	"Бензин и хот-доги для водителей.": "Gas and hot dogs for drivers.",
	"Автомойка": "Car wash",
	"Пена, щётки и сверкающие машины.": "Foam, brushes and sparkling cars.",
	"Автосервис": "Auto repair",
	"Меняем колёса и чиним моторы.": "We change wheels and fix engines.",
	"Автосалон": "Car dealership",
	"Новенькие кабриолеты с открытым верхом.": "Brand-new convertibles with the top down.",
	"Мотель": "Motel",
	"Придорожный мотель с неоновой вывеской.": "A roadside motel with a neon sign.",
	"Отель": "Hotel",
	"Высокий отель с бассейном на крыше. Туристы!": "A tall hotel with a rooftop pool. Tourists!",
	"Коворкинг": "Coworking",
	"Фрилансеры с ноутбуками и кофе.": "Freelancers with laptops and coffee.",
	"Банк": "Bank",
	"Хранилище монеток: сильно поднимает лимит монет.": "A coin vault: greatly raises the coin limit.",
	"Страховая компания": "Insurance company",
	"Страхуем хвосты от прищемления дверью.": "We insure tails against getting caught in doors.",
	"Юридическая фирма": "Law firm",
	"Адвокаты в строгих костюмах.": "Lawyers in sharp suits.",
	"Рекламное агентство": "Ad agency",
	"Придумывают слоганы для корма.": "They come up with slogans for cat food.",
	"Дизайн-бюро": "Design studio",
	"Логотипы, шрифты и мудборды.": "Logos, fonts and mood boards.",
	"Архитектурное бюро": "Architecture firm",
	"Проектируют когтеточки будущего. Стройки идут чуть быстрее.": "They design the scratching posts of the future. Construction goes a bit faster.",
	"Студия видеоигр": "Video game studio",
	"Делают хит «Котики против пылесоса».": "They make the hit «Cats vs. the Vacuum».",
	"Вычислительный центр": "Data center",
	"Серверы гудят, лампочки мигают. Тут живёт облако.": "Servers hum, lights blink. The cloud lives here.",
	"Студия звукозаписи": "Recording studio",
	"Здесь записывают хиты «Мур-мур-поп».": "«Purr-purr-pop» hits are recorded here.",
	"Радиостанция": "Radio station",
	"«Котоград FM» — лучшие песни о рыбе.": "«Kotograd FM» — the best songs about fish.",
	"Телецентр": "TV center",
	"Новости, ток-шоу и прогноз погоды (всегда солнечно).": "News, talk shows and the weather forecast (always sunny).",
	"Редакция газеты": "Newspaper office",
	"«Мурные вести» — свежий номер каждое утро.": "«The Purr Times» — a fresh issue every morning.",
	"Театр": "Theater",
	"Спектакль «Кот в сапогах» — аншлаг!": "«Puss in Boots» — sold out!",
	"Фабрика одежды": "Clothing factory",
	"Шьют пиджаки, худи и комбинезоны для всего города.": "They sew suits, hoodies and overalls for the whole city.",
	"Склад": "Warehouse",
	"Коробки, коробки, коробки! Сильно поднимает лимит еды.": "Boxes, boxes, boxes! Greatly raises the food limit.",
	"Грузовой порт": "Cargo port",
	"Краны и контейнеры. Ставится у воды.": "Cranes and containers. Placed by the water.",
	"Электростанция": "Power plant",
	"Даёт свет всему острову.": "Gives light to the whole island.",
	"Солнечная ферма": "Solar farm",
	"Солнце Калифорнии превращается в электричество.": "California sunshine turns into electricity.",
	"Водоочистная станция": "Water treatment plant",
	"Чистая вода из-под крана.": "Clean water from the tap.",
	"Сортировка мусора": "Recycling center",
	"Пластик к пластику, бумага к бумаге.": "Plastic with plastic, paper with paper.",
	"Суд": "Courthouse",
	"Судья в мантии разбирает спор о сметане.": "A judge in a robe settles a dispute over sour cream.",
	"Детский сад": "Kindergarten",
	"Котята играют, рисуют и спят после обеда.": "Kittens play, draw and nap after lunch.",
	"Университет": "University",
	"Факультет мурлыкологии и рыбной экономики.": "Faculty of purrology and fish economics.",
	"Научная лаборатория": "Science lab",
	"Учёные изобретают вечную лазерную точку.": "Scientists are inventing an everlasting laser dot.",
	"Станция метро": "Metro station",
	"Подземка: город становится ближе.": "The subway brings the city closer.",
	"Автовокзал": "Bus station",
	"Автобусы во все уголки острова.": "Buses to every corner of the island.",
	"Таксопарк": "Taxi depot",
	"Жёлтые такси с шашечками.": "Yellow checkered taxis.",
	"Вертолётная площадка": "Helipad",
	"Вертолётные экскурсии над побережьем.": "Helicopter tours over the coast.",
	"Скейт-парк": "Skate park",
	"Рампы и трюки как в Венис-бич.": "Ramps and tricks like at Venice Beach.",
	"Теннисный корт": "Tennis court",
	"Мячик туда-сюда, туда-сюда…": "The ball goes back and forth, back and forth…",
	"Пляжный волейбол": "Beach volleyball",
	"Сетка на песке у океана.": "A net on the sand by the ocean.",
	"Игровые автоматы": "Arcade",
	"Пиксельные игры — как эта!": "Pixel games — like this one!",
	"Боулинг": "Bowling alley",
	"Страйк! Кегли разлетаются.": "Strike! The pins go flying.",
	"Ночной клуб": "Nightclub",
	"Диско-шар и танцы до утра.": "A disco ball and dancing till dawn.",
	"Океанариум": "Aquarium",
	"Акулы, медузы и тысяча рыбок. Котики в восторге!": "Sharks, jellyfish and a thousand fish. The cats are delighted!",
	"Зоопарк": "Zoo",
	"Жирафы, пингвины и вольер с мышками.": "Giraffes, penguins and a mouse enclosure.",
	"Музей": "Museum",
	"Скелет древнего кота и картины с рыбами.": "The skeleton of an ancient cat and paintings of fish.",
	"Арт-галерея": "Art gallery",
	"Современное искусство: клубок на постаменте.": "Modern art: a yarn ball on a pedestal.",
	"Билборд": "Billboard",
	"Огромная реклама корма над дорогой.": "A giant cat food ad over the road.",
	"Водонапорная башня": "Water tower",
	"Старая башня — гордость района.": "An old tower — the pride of the neighbourhood.",
	"Дикая пальма. Можно убрать лопаткой за 2 монетки.": "A wild palm. Can be removed with the shovel for 2 coins.",
	"Агава": "Agave",
	"Колючая агава. Можно убрать лопаткой за 2 монетки.": "A prickly agave. Can be removed with the shovel for 2 coins.",
	"Камень": "Rock",
	"Можно убрать лопаткой за 2 монетки.": "Can be removed with the shovel for 2 coins.",
	"Рельеф": "Terrain",
	"Транспорт": "Transport",
	"Жильё": "Housing",
	"Магазины": "Shops",
	"Еда": "Food",
	"Услуги": "Services",
	"Бизнес": "Business",
	"Медиа": "Media",
	"Промышленность": "Industry",
	"Город": "City",
	"Отдых": "Leisure",
	"Природа": "Nature",
	"Чудеса": "Wonders",
	"Лапка": "Paw",
	"Двигай карту, гладь котиков, смотри постройки и машины.": "Move the map, pet cats, look at buildings and cars.",
	"Лопатка": "Shovel",
	"Убрать постройку (вернётся половина цены) или пальму/камень (2 мон.).": "Remove a building (half the price is refunded) or a palm/rock (2 coins).",
	"Рыбак": "Fisher",
	"Продавец": "Shop assistant",
	"Пекарь": "Baker",
	"Бариста": "Barista",
	"Офисный сотрудник": "Office worker",
	"Чиновник мэрии": "City hall official",
	"Рабочий фабрики": "Factory worker",
	"Строитель": "Builder",
	"Учитель": "Teacher",
	"Врач": "Doctor",
	"Полицейский": "Police officer",
	"Пожарный": "Firefighter",
	"Почтальон": "Mail carrier",
	"Библиотекарь": "Librarian",
	"Разработчик": "Developer",
	"Блогер": "Blogger",
	"Актёр": "Actor",
	"Серф-инструктор": "Surf instructor",
	"Фитнес-тренер": "Fitness trainer",
	"Мороженщик": "Ice cream seller",
	"Киномеханик": "Projectionist",
	"Спасатель": "Lifeguard",
	"Консультант техники": "Tech consultant",
	"Стилист": "Stylist",
	"Книготорговец": "Bookseller",
	"Продавец игрушек": "Toy seller",
	"Продавец зоотоваров": "Pet shop clerk",
	"Флорист": "Florist",
	"Фармацевт": "Pharmacist",
	"Кассир": "Cashier",
	"Продавец ТЦ": "Mall clerk",
	"Повар бургеров": "Burger cook",
	"Такверо": "Taquero",
	"Кондитер": "Pastry chef",
	"Чайный мастер": "Tea master",
	"Бармен фреш-бара": "Juice bartender",
	"Официант": "Waiter",
	"Фермер-торговец": "Market vendor",
	"Барбер": "Barber",
	"Массажист": "Masseur",
	"Инструктор йоги": "Yoga instructor",
	"Тату-мастер": "Tattoo artist",
	"Стоматолог": "Dentist",
	"Ветеринар": "Vet",
	"Работник прачечной": "Laundry worker",
	"Заправщик": "Gas attendant",
	"Мойщик машин": "Car washer",
	"Механик": "Mechanic",
	"Автодилер": "Car dealer",
	"Администратор мотеля": "Motel receptionist",
	"Консьерж": "Concierge",
	"Фрилансер": "Freelancer",
	"Банкир": "Banker",
	"Страховой агент": "Insurance agent",
	"Адвокат": "Lawyer",
	"Маркетолог": "Marketer",
	"Дизайнер": "Designer",
	"Архитектор": "Architect",
	"Геймдизайнер": "Game designer",
	"Сисадмин": "Sysadmin",
	"Музыкант": "Musician",
	"Радиоведущий": "Radio host",
	"Телеведущий": "TV host",
	"Журналист": "Journalist",
	"Актёр театра": "Stage actor",
	"Швея": "Seamstress",
	"Курьер": "Courier",
	"Докер": "Docker",
	"Электрик": "Electrician",
	"Инженер": "Engineer",
	"Сантехник": "Plumber",
	"Сортировщик": "Recycling sorter",
	"Судья": "Judge",
	"Воспитатель": "Kindergarten teacher",
	"Профессор": "Professor",
	"Учёный": "Scientist",
	"Машинист метро": "Metro driver",
	"Кондуктор": "Conductor",
	"Водитель автобуса": "Bus driver",
	"Таксист": "Taxi driver",
	"Пилот": "Pilot",
	"Скейтер": "Skater",
	"Тренер по теннису": "Tennis coach",
	"Смотритель автоматов": "Arcade attendant",
	"Работник боулинга": "Bowling alley worker",
	"Диджей": "DJ",
	"Морской биолог": "Marine biologist",
	"Смотритель зоопарка": "Zookeeper",
	"Куратор музея": "Museum curator",
	"Художник": "Artist",
	"Суши-повар": "Sushi chef",
	"Пиццайоло": "Pizzaiolo",
	"Грумер": "Groomer",
	"Фермер": "Farmer",
	"Трейдер": "Trader",
	"рыжий": "ginger",
	"серый": "grey",
	"белый": "white",
	"чёрный": "black",
	"трёхцветный": "calico",
	"сиамский": "Siamese",
	"полосатый": "tabby",
	"кремовый": "cream",
	"кот во фраке": "tuxedo",
	"рыжий полосатый": "ginger tabby",
	"лиловый": "lilac",
	"шоколадный": "chocolate",
	"русский голубой": "Russian blue",
	"бенгальский": "Bengal",
	"мейн-кун": "Maine Coon",
	"рэгдолл": "Ragdoll",
	"вислоухий": "Scottish fold",
	"сфинкс": "Sphynx",
	"черепаховый": "tortoiseshell",
	"снежный": "snow-white",
	"рыже-белый": "ginger and white",
	"дымчатый": "smoky",
	"коричный": "cinnamon",
	"золотистый": "golden",
	"серебристый": "silver",
	"чёрно-белый": "black and white",
	"Городские огни": "Urban Light",
	"Роща из старинных уличных фонарей. Вечером здесь все делают фото!": "A grove of vintage street lamps. In the evening everyone takes photos here!",
	"Голливуд-Боул": "Hollywood Bowl",
	"Концертная «ракушка» под открытым небом на склоне холма.": "An open-air concert «shell» on a hillside.",
	"Китайский кинотеатр Мяуманна": "Meowmann's Chinese Theatre",
	"Кинотеатр-пагода, а у входа — отпечатки лапок кинозвёзд.": "A pagoda cinema with movie stars' paw prints at the entrance.",
	"Башня Кэпитол-Мурекордс": "Capitol Purrcords Tower",
	"Круглая башня звукозаписи, похожая на стопку пластинок с иглой.": "A round recording tower that looks like a stack of records with a needle.",
	"Центр Гетти": "Getty Center",
	"Белый музей на вершине холма с садами и видом на океан. Строится только на холмах и в горах.": "A white hilltop museum with gardens and an ocean view. Built only on hills and mountains.",
	"Такси!": "Taxi!",
	"Одностороннее движение": "One-way street",
	"Проведите по дороге — она станет односторонней в эту сторону, и машины поедут по ней в две полосы. Нажатие на дорогу меняет направление по кругу, ещё раз — снова двустороннее. Бесплатно.": "Drag along a road to make it one-way in that direction — cars will use both lanes. Clicking a road cycles the direction, and once more makes it two-way again. Free.",
	"Проведите по обычной дороге": "Drag along a regular road",
	"Коробки, коробки, коробки! Сильно поднимает лимит еды. Принимает лишние товары и сам развозит их своими грузовиками туда, где они нужны.": "Boxes, boxes, boxes! Greatly raises the food limit. Takes in surplus goods and sends them by its own trucks wherever they are needed.",
	"Краны и контейнеры. Ставится у воды. Покупает лишние товары на экспорт — грузовики везут сюда всё, что не нужно городу.": "Cranes and containers. Placed by the water. Buys surplus goods for export — trucks bring here everything the city does not need.",
	"Молочная ферма": "Dairy farm",
	"Коровы, сено и самое вкусное молоко. Молоко ждут кафе, мороженое, бабл-ти, пекарни и пончиковые.": "Cows, hay and the tastiest milk. Cafes, ice cream kiosks, bubble tea, bakeries and donut shops need milk.",
	"Овечья ферма": "Sheep farm",
	"Пушистые овечки дают шерсть. Из неё на Фабрике клубков делают клубки.": "Fluffy sheep give wool. The Yarn factory turns it into yarn balls.",
	"Хлопковое поле": "Cotton field",
	"Белые коробочки хлопка. Хлопок нужен Фабрике одежды.": "White cotton bolls. The Clothing factory needs cotton.",
	"Лесопилка": "Sawmill",
	"Пилит доски. Доски нужны Мебельной фабрике, Стройконторе и архитекторам.": "Saws planks. Planks are needed by the Furniture factory, the Construction company and architects.",
	"Рудник": "Mine",
	"Добывает металл в горах. Строится на холмах и в горах. Металл нужен Заводу электроники и автомастерам.": "Mines metal in the mountains. Built on hills and mountains. Metal is needed by the Electronics plant and car workshops.",
	"Мукомольня": "Flour mill",
	"Мелет урожай с фермы в муку. Мука нужна пекарням, пиццериям, пончиковым и бургерным.": "Grinds the farm harvest into flour. Bakeries, pizzerias, donut shops and burger joints need flour.",
	"Мебельная фабрика": "Furniture factory",
	"Делает диваны и кресла из досок. Мебель ждут торговые центры, отели, мотели и офисы.": "Makes sofas and armchairs from planks. Malls, hotels, motels and offices need furniture.",
	"Завод электроники": "Electronics plant",
	"Собирает телефоны и приставки из металла. Электроника нужна магазинам техники, айти-компаниям, игровым студиям и вычислительным центрам.": "Assembles phones and consoles from metal. Tech stores, IT companies, game studios and data centers need electronics.",
	"Лодочная пристань": "Boat dock",
	"Деревянные мостки и моторная лодка. Днём котики катаются по заливу. Ставится у воды.": "Wooden boardwalk and a motorboat. In the daytime cats ride around the bay. Placed by the water.",
	"Яхт-клуб": "Yacht club",
	"Белые яхты под парусами. Днём они выходят в залив с котиками на борту, а туристы приезжают на них посмотреть. Ставится у воды.": "White yachts under sail. In the daytime they go out into the bay with cats on board, and tourists come to watch. Placed by the water.",
	"Доярка": "Milkmaid",
	"Пастух": "Shepherd",
	"Лесоруб": "Lumberjack",
	"Шахтёр": "Miner",
	"Мельник": "Miller",
	"Столяр": "Carpenter",
	"Капитан яхты": "Yacht captain",
	"Сборщик электроники": "Electronics assembler",
	"Рыба": "Fish",
	"Урожай": "Harvest",
	"Молоко": "Milk",
	"Шерсть": "Wool",
	"Хлопок": "Cotton",
	"Доски": "Planks",
	"Металл": "Metal",
	"Мука": "Flour",
	"Клубки": "Yarn",
	"Одежда": "Clothes",
	"Мебель": "Furniture",
	"Электроника": "Electronics",
	"Производит: %s": "Produces: %s",
	"Перерабатывает: %s → %s": "Processes: %s → %s",
	"Ждёт товары: %s": "Needs goods: %s",
	"Производит: %s — готово к отправке %d из %d": "Produces: %s — ready to ship %d of %d",
	"  Сырьё: %s — %d": "  Input: %s — %d",
	"  Ждёт сырьё: %s привезут грузовики от «%s»": "  Waiting for %s — trucks bring it from «%s»",
	"  Работает на полную: доход +50%": "  Running at full capacity: income +50%",
	"  Без работников производство стоит.": "  Without workers production stands still.",
	"  Подведите дорогу — грузовикам не выехать.": "  Build a road — trucks cannot get out.",
	"Товары: %s": "Goods: %s",
	"  С товарами доход выше: +%d%%": "  Goods in stock raise income: +%d%%",
	"  Нужно: %s — от «%s»": "  Needs: %s — from «%s»",
	"На складе: %s": "In storage: %s",
	"пусто": "empty",
	"Продано на экспорт: %d": "Sold for export: %d",
	"Первая поставка": "First delivery",
	"Грузовик должен привезти товар: поставьте у дороги причал или ферму и суши-бар, рынок или фреш-бар": "A truck must deliver goods: place a pier or a farm by a road, plus a sushi bar, market or juice bar",
	"Производственная цепочка": "Production chain",
	"Запустите переработку: например, Мукомольня мелет урожай с фермы в муку": "Start processing: for example, a Flour mill grinds the farm harvest into flour",
	"Логистика": "Logistics",
	"Грузовики сделали 100 поставок": "Trucks made 100 deliveries",
	"Сделано в Котограде": "Made in Kotograd",
	"Продайте 100 товаров через грузовой порт": "Sell 100 goods through the cargo port",
	"Полный цикл": "Full cycle",
	"Запустите все 5 перерабатывающих производств": "Run all 5 processing plants",
}
